### ISSUE TITLE
发现两个小问题，情有时间修改一下

### ISSUE THREAD

**Issue by jackiehu** [HeathWang/HWPanModal#10]
panScrollable的滚动条请隐藏，触感反馈ipad闪退

**Comment by jackiehu** [comment]
- (void)trackScrolling:(UIScrollView *)scrollView {
	self.scrollViewYOffset = MAX(scrollView.contentOffset.y, 0);
	scrollView.showsVerticalScrollIndicator = YES;
}
这行代码会导致滚动条隐藏失效；

触感反馈某些ipad机型闪退

**Comment by HeathWang** [comment]
> 触感反馈某些ipad机型闪退

能提供具体机型和系统版本吗？谢谢

scrollIndicator会先检查用户设置的隐藏与否，近期改进。

**Comment by HeathWang** [comment]
@jackiehu 
`pod 'HWPanModal', '~> 0.2.9.1'`
闪退麻烦提供一下详细信息

**Comment by jackiehu** [comment]
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x157f2a790>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'

ipad air ios12.3

**Comment by HeathWang** [comment]
`pod 'HWPanModal', '~> 0.2.9.2'`
@jackiehu 
Thanks.
