### ISSUE TITLE
使用[self dismissViewControllerAnimated:YES completion:nil];返回问题

### ISSUE THREAD

**Issue by rhwish** [HeathWang/HWPanModal#100]
1.使用UINavigationController(已遵守HWPanModalPresentable协议)包裹ControllerA
2.使用[self presentPanModal:navController];显示ControllerA
3.在ControllerA中使用[self dismissViewControllerAnimated:YES completion:nil];返回
此时ControllerA不dealloc，但是拖拽或者点空白隐藏ControllerA时会执行dealloc

**Comment by HeathWang** [comment]
我看下

**Comment by HeathWang** [comment]
我试了下，2种方式都走了dealloc方法的，或者你提供你的2个vc给我试下

**Comment by HeathWang** [comment]
使用拖拽最终也是调用
```

[self.presentedViewController dismissViewControllerAnimated:YES completion:^{
		[self.presentable panModalDidDismissed];
	}];
```

**Comment by rhwish** [comment]
找到原因了，我为了在token过期时自动跳转登录界面，在全局持有了当前的presentable的VC，没有在dismiss之前释放持有导致的。非常感谢您~
