### ISSUE TITLE
视图消失后依旧能响应上拉手势

### ISSUE THREAD

**Issue by CuanXiangDeYun** [HeathWang/HWPanModal#102]
**Bug描述**
视图消失时候的依旧能响应上拉手势将视图拉出来,然后再remove, 视觉上异常闪现.

**复现步骤**
1. 触发dismiss
2. 视图在屏幕内消失不见的时候立即上滑
3. 上滑过程中发现原来消失的视图又展示出来了
4. 很快又 remove 掉了

这种情况在容器内的视图时滚动列表的时候尤为明显.

感谢作者的开源框架,期待修复.

**Comment by HeathWang** [comment]
应该是动画还没有完全结束，这时候alpha接近于0，看起来已经完全消失。
下个版本会改进在dismiss时禁用userInteractionEnabled

**Comment by HeathWang** [comment]
你使用的那个版本，我试了下并无法复现

**Comment by CuanXiangDeYun** [comment]
就是最新版本,下载了您的demo,也复现了具体在 `Use PanModal View ` 里面的 第二个和第三个示例. 
目前看应该是只要继承自 `HWPanModalContentView` 的都会出现

**Comment by HeathWang** [comment]
> 就是最新版本,下载了您的demo,也复现了具体在 `Use PanModal View ` 里面的 第二个和第三个示例.
> 目前看应该是只要继承自 `HWPanModalContentView` 的都会出现
> 
> [复现视频](https://github.com/CuanXiangDeYun/images/blob/master/bugfeedback.mp4)

我以为是controller dismiss出现问题，一直没复现

**Comment by HeathWang** [comment]
请使用0.8.9版本试下，问题应该解决了

**Comment by CuanXiangDeYun** [comment]
> 请使用0.8.9版本试下，问题应该解决了
> 
> @GandjaFuzz

**Comment by CuanXiangDeYun** [comment]
好嘞,我更新下,感谢~
