### ISSUE TITLE
上滑或者下滑过程中实时获得弹框的高度

### ISSUE THREAD

**Issue by shanglina** [HeathWang/HWPanModal#104]
作者您好，
需求是在上升到long或者下滑到short的过程中UI做一些变化，怎么可以实时拿到当前的高度呢
第二个是弹出视图的时候是否可以直接选择升起到long还是short呢？
辛苦啦~

**Comment by shanglina** [comment]
实时拿到当前的高度可以了，升起的时候在外部直接选择选择升起到long还是short还是没找到。
另一个就是可以禁用动画吗？

**Comment by shanglina** [comment]
需求是进来的时候 就以short的状态展示在屏幕上了

**Comment by HeathWang** [comment]
```
/**
 * 初始弹出高度状态，默认为`shortFormHeight`
 *
 * Origin presentation height state, if you have special requirement, change it.
 * Default is `shortFormHeight`
 */
- (PresentationState)originPresentationState;
```
仔细看下文档，或者跑下example，大部分问题都可以找到答案。

**Comment by HeathWang** [comment]
```
/// which view that your presented viewController's view has been added.
@property (nonatomic, readonly) UIView *hw_contentView;
```
这个view的frame就是你的视图所在的

**Comment by shanglina** [comment]
originPresentationState 这个不可以初始化的时候赋值吧？

另外第一次弹出的时候可以禁用动画吗？
辛苦辛苦 感恩

**Comment by HeathWang** [comment]
> originPresentationState 这个不可以初始化的时候赋值吧？
> 
> 另外第一次弹出的时候可以禁用动画吗？
> 辛苦辛苦 感恩

originPresentationState就是刚开始的状态
目前没有禁用动画，你把动画时长返回0不就好了

**Comment by shanglina** [comment]
你好， 如果设置
[self presentViewController:viewControllerToPresent animated:NO completion:completion];的时候，可以实现进入页面的时候，被弹出的控制器就展示在页面上，但是位置不对，如果设置动画时间是0的话，会卡顿，anitmation=yes的时候 弹出会有延迟呢，是在主线程执行的。需求是进来的时候 就以short的状态展示在屏幕上了 这个需求您有什么思路可以提供下吗？我这边再试一下

**Comment by HeathWang** [comment]
建议使用`HWPanModalContentView`来实现该需求

**Comment by HeathWang** [comment]
长期未回复，关闭
