### ISSUE TITLE
弹出多层dismiss的问题

### ISSUE THREAD

**Issue by chenjc0317** [HeathWang/HWPanModal#106]
版本：0.6.7
**问题：根视图弹出VC，VC弹出一个继承'HWPanModalContentView'的View，下拉view时，VC也会跟着下拉。**
我现在的解决步骤：在VC中创建一个控制变量，当view弹出时设置为false，view dismiss完成后设置为true，实现‘shouldRespondToPanModalGestureRecognizer’方法。
想问一下，有没有可能在手势层面解决这个问题。
感激不尽

第一层VC：
![image](https://user-images.githubusercontent.com/47734570/143796118-68b59bee-82a0-41c9-8f5a-10bdac3c677b.png)
第二层view：
![image](https://user-images.githubusercontent.com/47734570/143796149-cb168e72-345a-4823-a09e-4a282977af6e.png)
复现视频:

https://user-images.githubusercontent.com/47734570/143796417-410218e3-36b0-4558-8ca0-14e2416fcddc.mp4

**Comment by chenjc0317** [comment]
@HeathWang

**Comment by HeathWang** [comment]
@chenjc0317 可以第二个视图也用ViewController弹出的
