### ISSUE TITLE
#CRASH  

### ISSUE THREAD

**Issue by devSC** [HeathWang/HWPanModal#107]
**Smartphone (please complete the following information):**
47% iOS 15
47% iOS 14
6% iPadOS 14

**Additional context**

Crashed: com.apple.main-thread
0  UIKitCore                      0x3e37f4 -[UIView(AdditionalLayoutSupport) _uili_existingBaseFrameVariables] + 4
1  UIKitCore                      0x1cf200 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 452
2  UIKitCore                      0x3bd804 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 216
3  UIKitCore                      0x1e1748 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke_2 + 188
4  CoreAutoLayout                 0x85f8 -[NSISEngine withBehaviors:performModifications:] + 88
5  UIKitCore                      0x1cf26c __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke + 560
6  UIKitCore                      0x3bd804 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:] + 216
7  UIKitCore                      0x1dfdbc __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 100
8  CoreAutoLayout                 0x85f8 -[NSISEngine withBehaviors:performModifications:] + 88
9  UIKitCore                      0x26eff4 -[UIView(Hierarchy) _postMovedFromSuperview:] + 836
10 UIKitCore                      0x18b8d4 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 2148
11 UIKitCore                      0x3b3c2c -[UITableView _addSubview:positioned:relativeTo:] + 108
12 UIKitCore                      0x24bcf8 CreateScrollIndicator + 364
13 UIKitCore                      0x31e11c -[UIScrollView _adjustScrollerIndicators:alwaysShowingThem:] + 276
14 UIKitCore                      0x254334 -[UITableView _updateShowScrollIndicatorsFlag] + 376
15 HWPanModal                     0xd658 -[HWPanModalPresentableHandler trackScrolling:] + 340 (HWPanModalPresentableHandler.m:340)
16 HWPanModal                     0xd858 -[HWPanModalPresentableHandler didPanOnScrollViewChanged:] + 386 (HWPanModalPresentableHandler.m:386)
17 HWPanModal                     0x15a9c -[KeyValueObserver didChange:] + 75 (KeyValueObserver.m:75)
18 Foundation                     0x3204c NSKeyValueNotifyObserver + 292
19 Foundation                     0x1d460 NSKeyValueDidChange + 356
20 Foundation                     0x2bf78 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 644
21 Foundation                     0x21c5c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
22 Foundation                     0x1fc8c _NSSetPointValueAndNotify + 328
23 UIKitCore                      0x1c9c0c -[UIScrollView _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:animation:animationConfigurator:] + 824
24 HWPanModal                     0xd6cc -[HWPanModalPresentableHandler haltScrolling:] + 349 (HWPanModalPresentableHandler.m:349)
25 HWPanModal                     0xd858 -[HWPanModalPresentableHandler didPanOnScrollViewChanged:] + 386 (HWPanModalPresentableHandler.m:386)
26 HWPanModal                     0x15a9c -[KeyValueObserver didChange:] + 75 (KeyValueObserver.m:75)
27 Foundation                     0x3204c NSKeyValueNotifyObserver + 292
28 Foundation                     0x1d460 NSKeyValueDidChange + 356
29 Foundation                     0x2bf78 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 644
30 Foundation                     0x21c5c -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 72
31 Foundation                     0x1fc8c _NSSetPointValueAndNotify + 328
32 UIKitCore                      0x2ae9ac -[UITableView _updateVisibleCellsNow:] + 2356
33 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
34 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
35 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
36 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
37 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
38 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
39 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
40 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
41 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
42 UIKitCore                      0x2ae9e0 -[UITableView _updateVisibleCellsNow:] + 2408
43 UIKitCore                      0x17d8a8 -[UITableView layoutSubviews] + 456
44 UIKitCore                      0x18ded8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2620
45 QuartzCore                     0x3fe24 CA::Layer::layout_if_needed(CA::Transaction*) + 536
46 QuartzCore                     0x32644 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144
47 QuartzCore                     0x46c6c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 524
48 QuartzCore                     0x4f560 CA::Transaction::commit() + 680
49 QuartzCore                     0x31dac CA::Transaction::flush_as_runloop_observer(bool) + 88
50 CoreFoundation                 0x41560 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
51 CoreFoundation                 0x10844 __CFRunLoopDoObservers + 572
52 CoreFoundation                 0xb8dc __CFRunLoopRun + 1052
53 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
54 GraphicsServices               0x138c GSEventRunModal + 164
55 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
56 UIKitCore                      0x2987f4 UIApplicationMain + 2092
57 ***                      0xb9b4 main + 42 (AppDelegate.swift:42)
58 ???                            0x103ff1a24 (Missing)

**Comment by devSC** [comment]
这个还没找到复现方法

**Comment by iBlackStone** [comment]
我也遇到了同样的问题，请问修复了吗？在你的业务场景中

**Comment by lchenfox** [comment]
Crash demo: [HWPanModal Crash Demo](https://github.com/lchenfox/HWPanModalCrashDemo.git). And I create a PR to fix this issue.

**Comment by HeathWang** [comment]
> Crash demo: [HWPanModal Crash Demo](https://github.com/lchenfox/HWPanModalCrashDemo.git). And I create a PR to fix this issue.

Nice. As I can not produce this crash, so this issue can not resolve.
Later I will check the PR.
Thank you so much.

**Comment by HeathWang** [comment]
HWPanModal (0.9.4) successfully published, fix this crash.
If this crash exists again, pls reopen it.
@devSC @iBlackStone @lchenfox @GandjaFuzz

**Comment by devSC** [comment]
线上还是会崩的

**Comment by pandaleecn** [comment]
请问有解决方案吗？这个崩溃目前在我们Firebase排在首位。

# Issue: d613e968aae6ac852c7ef1e792783c8d
# Session: 596156ebd9c440faa9ff4359c5d6dd0c_DNE_0_v2
# Date: Sun Jan 07 2024 04:35:08 GMT+0800 (中国标准时间)

Crashed: com.apple.main-thread
0  libsystem_c.dylib              0x9800 localeconv_l + 4
1  libsystem_c.dylib              0x1f74 _vsnprintf + 224
2  libsystem_c.dylib              0x5df8 snprintf_l + 32
3  CoreFoundation                 0x50f30 __CFStringAppendFormatCore + 9436
4  CoreFoundation                 0x841d4 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 184
5  CoreFoundation                 0x80aac _CFStringCreateWithFormatAndArgumentsAux2 + 44
6  Foundation                     0x1aeb8 +[NSString stringWithFormat:] + 68
7  FBSDKCoreKit                   0x61880 +[FBSDKSwizzler object:ofClass:isCallingSelector:] + 339 (FBSDKSwizzler.m:339)
8  FBSDKCoreKit                   0x624e8 fb_findSwizzle + 67 (FBSDKSwizzler.m:67)
9  FBSDKCoreKit                   0x61dc8 fb_swizzledMethod_2 + 90 (FBSDKSwizzler.m:90)
10 UIKitCore                      0x1d0c8 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1812
11 UIKitCore                      0x1cc6c -[UIView(Internal) _didMoveFromWindow:toWindow:] + 696
12 UIKitCore                      0xd0248 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 112
13 CoreAutoLayout                 0x4e70 -[NSISEngine withBehaviors:performModifications:] + 84
14 UIKitCore                      0x105d858 -[UIView _postMovedFromSuperview:] + 672
15 UIKitCore                      0x1ddf4 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1952
16 UIKitCore                      0x93af0 -[UITableView _addSubview:positioned:relativeTo:] + 100
17 UIKitCore                      0x145058 CreateScrollIndicator + 292
18 UIKitCore                      0x52a6c -[UIScrollView _adjustScrollerIndicators:alwaysShowingThem:] + 240
19 UIKitCore                      0x102740 -[UITableView _updateShowScrollIndicatorsFlag] + 308
20 HelloTalk_Binary               0x210c244 -[HWPanModalPresentableHandler trackScrolling:] + 301 (HWPanModalPresentableHandler.m:301)
21 HelloTalk_Binary               0x210c3a0 -[HWPanModalPresentableHandler didPanOnScrollViewChanged:] + 336 (HWPanModalPresentableHandler.m:336)
22 HelloTalk_Binary               0x21134bc -[KeyValueObserver didChange:] + 69 (KeyValueObserver.m:69)
23 Foundation                     0x3c0d0 NSKeyValueNotifyObserver + 252
24 Foundation                     0x52618 NSKeyValueDidChange + 356
25 Foundation                     0x3f518 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 680
26 Foundation                     0x3f248 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 64
27 Foundation                     0x3f1cc _NSSetPointValueAndNotify + 300
28 UIKitCore                      0x55784 -[UIScrollView _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:animation:animationConfigurator:] + 588
29 HelloTalk_Binary               0x210c2c4 -[HWPanModalPresentableHandler haltScrolling:] + 319 (HWPanModalPresentableHandler.m:319)
30 HelloTalk_Binary               0x210c3d4 -[HWPanModalPresentableHandler didPanOnScrollViewChanged:] + 357 (HWPanModalPresentableHandler.m:357)
31 HelloTalk_Binary               0x21134bc -[KeyValueObserver didChange:] + 69 (KeyValueObserver.m:69)
32 Foundation                     0x3c0d0 NSKeyValueNotifyObserver + 252
33 Foundation                     0x52618 NSKeyValueDidChange + 356
34 Foundation                     0x3f518 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 680
35 Foundation                     0x3f248 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 64
36 Foundation                     0x3f1cc _NSSetPointValueAndNotify + 300
37 UIKitCore                      0x56ae4 -[UITableView _updateVisibleCellsNow:] + 1784
38 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
39 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
40 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
41 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
42 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
43 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
44 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
45 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
46 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
47 UIKitCore                      0x56b0c -[UITableView _updateVisibleCellsNow:] + 1824
48 UIKitCore                      0x56320 -[UITableView layoutSubviews] + 148
49 UIKitCore                      0x4420 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1992
50 QuartzCore                     0x9f30 CA::Layer::layout_if_needed(CA::Transaction*) + 500
51 UIKitCore                      0xceb30 -[UIView(Hierarchy) layoutBelowIfNeeded] + 296
52 HelloTalk_Binary               0x213fd14 -[UIViewController(PanModalDefault) allowsExtendedPanScrolling] + 104 (UIViewController+PanModalDefault.m:104)
53 HelloTalk_Binary               0x210c890 -[HWPanModalPresentableHandler configureViewLayout] + 419 (HWPanModalPresentableHandler.m:419)
54 HelloTalk_Binary               0x2110658 -[HWPanModalPresentationController configureViewLayout] + 315 (HWPanModalPresentationController.m:315)
55 HelloTalk_Binary               0x210f6dc -[HWPanModalPresentationController setNeedsLayoutUpdate] + 151 (HWPanModalPresentationController.m:151)
56 HelloTalk_Binary               0x2140388 -[UIViewController(Presentation) hw_panModalSetNeedsLayoutUpdate] + 41 (UIViewController+Presentation.m:41)
57 HelloTalk_Binary               0x3cf5aa8 partial apply for closure #1 in VoiceRVisitorViewController.bindViewModel() + 73 (VoiceRVisitorViewController.swift:73)
58 HelloTalk_Binary               0x5063e50 partial apply for closure #1 in ObservableType.subscribe(_:) + 22 (ObservableType+Extensions.swift:22)
59 HelloTalk_Binary               0x50177f0 AnonymousObserver.onCore(_:) + 23 (AnonymousObserver.swift:23)
60 HelloTalk_Binary               0x50667bc ObserverBase.on(_:) + 16 (ObserverBase.swift:16)
61 HelloTalk_Binary               0x5066900 protocol witness for ObserverType.on(_:) in conformance ObserverBase<A> + 6102948 (<compiler-generated>:6102948)
62 HelloTalk_Binary               0x5065a70 closure #1 in ObserveOnSerialDispatchQueueSink.init(scheduler:observer:cancel:) + 196 (ObserveOn.swift:196)
63 HelloTalk_Binary               0x506638c partial apply for thunk for @escaping @callee_guaranteed (@guaranteed ObserveOnSerialDispatchQueueSink<A>, @in_guaranteed Event<A.ObserverType.Element>) -> (@out Disposable) + 6101552 (<compiler-generated>:6101552)
64 HelloTalk_Binary               0x50454d8 partial apply for closure #1 in DispatchQueueConfiguration.schedule<A>(_:action:) + 27 (DispatchQueueConfiguration.swift:27)
65 HelloTalk_Binary               0x8477c thunk for @escaping @callee_guaranteed () -> () + 4330915708 (<compiler-generated>:4330915708)
66 libdispatch.dylib              0x2320 _dispatch_call_block_and_release + 32
67 libdispatch.dylib              0x3eac _dispatch_client_callout + 20
68 libdispatch.dylib              0x126a4 _dispatch_main_queue_drain + 928
69 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
70 CoreFoundation                 0x98c28 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
71 CoreFoundation                 0x7a560 __CFRunLoopRun + 1992
72 CoreFoundation                 0x7f3ec CFRunLoopRunSpecific + 612
73 GraphicsServices               0x135c GSEventRunModal + 164
74 UIKitCore                      0x39cf58 -[UIApplication _run] + 888
75 UIKitCore                      0x39cbbc UIApplicationMain + 340
76 HelloTalk_Binary               0x54ff7f8 main + 25 (main.m:25)
77 ???                            0x1e1174dec (缺少)
