### ISSUE TITLE
关于scrollview 和侧滑手势

### ISSUE THREAD

**Issue by MuRanJiangXia** [HeathWang/HWPanModal#108]
侧滑返回导航的手势 和 scrollview 下滑的手势冲突了，这个可以解决吗？侧滑的时候 scrollview也会向下滑动

**Comment by MuRanJiangXia** [comment]
自定义的scrollview 没事， wkwebview 的scrollview 会出现手势冲突

**Comment by HeathWang** [comment]
有相关代码吗，我来试下
