### ISSUE TITLE
键盘输入缩进怎么取消。之前是界面平铺的输入框正好能看到。现在点击输入界面缩进了。不使用这种自动缩进的。

### ISSUE THREAD

**Issue by 3125825529** [HeathWang/HWPanModal#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 3125825529** [comment]
- (BOOL)isAutoHandleKeyboardEnabled{
    return NO;
}

**Comment by HeathWang** [comment]
> * (BOOL)isAutoHandleKeyboardEnabled{
>   return NO;
>   }

这个没有效果吗？
