### ISSUE TITLE
使用HWPanModalContainerView 在iPad分屏的时候控制app展示区域宽度   HWPanModalContainerView的frame异常

### ISSUE THREAD

**Issue by TomasWell** [HeathWang/HWPanModal#110]
使用HWPanModalContainerView 在iPad分屏的时候控制app展示区域宽度   HWPanModalContainerView的frame异常
临时解决方案
HWPanModalContainerView
在adjustPresentedViewFrame中第一行加上代码
self.frame = self.presentingView.bounds;
可暂时解决
更完善的还得等待大佬的解决方案

**Comment by HeathWang** [comment]
> 使用HWPanModalContainerView 在iPad分屏的时候控制app展示区域宽度 HWPanModalContainerView的frame异常
> 临时解决方案
> HWPanModalContainerView
> 在adjustPresentedViewFrame中第一行加上代码
> self.frame = self.presentingView.bounds;
> 可暂时解决
> 更完善的还得等待大佬的解决方案

抱歉，没在ipad测试过分屏场景，我看下
