### ISSUE TITLE
使用modal动画后， 调用    [self.presentingViewController dismissViewControllerAnimated:false completion:nil];导致整个app导航控制器push动画失效

### ISSUE THREAD

**Issue by yw0911** [HeathWang/HWPanModal#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
我也复现了，请使用弹出的presented VC来dismiss
```
[self dismissViewControllerAnimated:NO completion:^{
        
    }];
```
或者弱持有presented VC，在合适的实际dismiss

**Comment by HeathWang** [comment]
[self.presentingViewController dismissViewControllerAnimated:false completion:nil];
当animated为NO，并不会触发组件内部的转场动画，由UIKit内部代码完成dismiss操作，本身无法控制。
