### ISSUE TITLE
嗨，大神，这个问题能不能帮忙解决一下，我这边是要求能够侧滑返回的，还有个需求就是 我想做成demo 里知乎的效果，我看了demo是 present到了一个Nav里，能不能在上面也加个箭头。感觉这个效果很好看> 1.present出navigationController之后，push到其他Controller滑动返回时，不是返回上一个Controller，而点击返回按钮可以返回上一个Controller，能不能滑动返回时可以返回上一个Controller

### ISSUE THREAD

**Issue by icNaoki** [HeathWang/HWPanModal#114]
> 1.present出navigationController之后，push到其他Controller滑动返回时，不是返回上一个Controller，而点击返回按钮可以返回上一个Controller，能不能滑动返回时可以返回上一个Controller

滑动返回自己可以控制的

注释掉
```
//- (BOOL)allowScreenEdgeInteractive {
//    return YES;
//}
```

_Originally posted by @HeathWang in https://github.com/HeathWang/HWPanModal/issues/88#issuecomment-808045506_

**Comment by HeathWang** [comment]
no reply, close it
