### ISSUE TITLE
Dismiss 全部控制器问题

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#117]
```
- (void)adt_dismissAllViewControllerAnimated:(BOOL)flag completion: (void (^ __nullable)(void))completion {
    
    UIViewController *vc = self;
    while (vc.presentingViewController) {
        vc = vc.presentingViewController;
    }
    [vc dismissViewControllerAnimated:flag completion:completion];
}
```
场景：全部通过 present方式  A -> B ->C -> D  ， 我通过获取到A控制器的方式 dismiss 所有presentingViewController，A/B/C的遮罩并没有进行动画，而是控制器消失时 瞬间移除的。能否全部通过动画的形势往下收回？

**Comment by HeathWang** [comment]
我看下能不能把API暴露出来，可以主动通过动画往下消失。

**Comment by HeathWang** [comment]
HWPanModal (0.9.2)
增加了api：`- (void)hw_dismissAnimated:(BOOL)animated completion:(void (^)(void))completion`可以给每个vc单独dismiss
