### ISSUE TITLE
键盘回避能关闭吗?

### ISSUE THREAD

**Issue by CivelXu** [HeathWang/HWPanModal#12]

**Comment by CivelXu** [comment]
有输入框, 界面滑动不了了

**Comment by HeathWang** [comment]
输入状态是无法滑动的，如果是view，点击空白，endediting，如果是scrollView，处理drag回调
结束输入状态即可正常滑动。

**Comment by CivelXu** [comment]
@HeathWang 希望这个特性能给个开关 不要这么粗暴 😳

**Comment by HeathWang** [comment]
@CivelXu 你先这样做，这几天加上

**Comment by HeathWang** [comment]
@CivelXu 
pod 'HWPanModal', '~> 0.2.9.3'
```
- (BOOL)isAutoHandleKeyboardEnabled {
	return NO;
}
```
