### ISSUE TITLE
您好，高度动态计算后有部分黑屏

### ISSUE THREAD

**Issue by LYluyu** [HeathWang/HWPanModal#124]
https://user-images.githubusercontent.com/16254669/177005979-f8373c9b-ed55-44d8-bea0-7bbd993033fe.mov

如视频所示，我的弹出框是通过tableView来动态计算的，当第二个tableView高度比较高时，再点击回第一个，就会出现黑屏

**Comment by HeathWang** [comment]
有参照example里的代码来实现吗？example里有2个tableView来回切换的。

**Comment by HeathWang** [comment]
no reply, close it
