### ISSUE TITLE
手势代理能否抛出？

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#128]
我有一个横向滚动的UICollectionView，需要shouldRecognizeSimultaneouslyWithGestureRecognizer这个代理方法，来对其进行判断，横向滚动时响应我自己的view，禁用下滑dismiss，纵向时禁用我的View，响应下滑dismiss

**Comment by HeathWang** [comment]
可以，我看下

**Comment by fuchenxi** [comment]
我建议所有的都抛出。
因为复杂的手势需求这种代理都需要使用。 还有就是建议代理API可以优化更新个大版本了，这个库我也用了很多年了。整体使用感觉挺不错的，就是实现代理方法还是觉得有些啰嗦了。可以出一个类似于 `UIAppearance` 的全局配置项，适用于整体，控制器的方法，改成属性比如 :
```
vc.hw_pushAnimation.springDamping
vc.hw_popAnimation.springDamping
vc.hw_interaction
```
`hw_pushAnimation` 、 `hw_popAnimation`、`vc.hw_interaction` 可以遵循某个协议，让客户端可以自定义实现。
`-presentPanModal:` 改成 hook 系统的 `presentViewController:`, 使用自己的还是系统的，可以给控制器添加一个开关属性。
总的来说，就是 动画、手势、交互等都可以单独剥离开。现在在一个协议里确实越来越复杂啦。
只是建议~~~这是个大工程

**Comment by HeathWang** [comment]
拆分的协议越多，颗粒度是变小了，但是一般人刚入手理解使用也难度加大。
原本做的很简单，后面发现提的需求越来越多，一个协议就变得很大了。

我看看把所有的手势代理抛出来吧。
拆协议不确保不出bug，目前没这个计划，毕竟测试全靠同行。

**Comment by HeathWang** [comment]
@fuchenxi 

```
pod 'HWPanModal', :git => 'https://github.com/HeathWang/HWPanModal.git'
```
我提交了，你看下能满足你的要求吗？没问题再发release

**Comment by fuchenxi** [comment]
好的，我这两天忙完这个需求，我再测试下。完事告诉你

**Comment by fuchenxi** [comment]
@HeathWang 
四个手势全都抛出来了，是可行的。

之前的问题是模态出一个VC，里面嵌套一个横向滚动的CollectionView，会出现既可横向滚动CollectionView，也能纵向滚动Dimiss VC，主要是由于以下代码导致两个手势都可以识别。

目前我看是添加个协议`HWPanModalPanGestureDelegate`，只要实现协议的方法，直接就return了。我不用做什么事情，默认就是我想要的功能。

```
HWPanModalPresentableHandler.m
/**
 * ONLY When otherGestureRecognizer is panGestureRecognizer, and target gestureRecognizer is panGestureRecognizer, return YES.
 */
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    if ([gestureRecognizer isKindOfClass:UIPanGestureRecognizer.class]) {
        return [otherGestureRecognizer isKindOfClass:UIPanGestureRecognizer.class];
    }
    return NO;
}
```

**Comment by HeathWang** [comment]
ok，那我发布新version

**Comment by HeathWang** [comment]
@fuchenxi 
指定版本：0.9.5

**Comment by fuchenxi** [comment]
好的。我更新一下
