### ISSUE TITLE
里面有UIWebView 注释审核过不了 ,建议更新

### ISSUE THREAD

**Issue by JadeXH** [HeathWang/HWPanModal#129]
./Pods/HWPanModal/README-CN.md:1. 任何情况下，内部嵌套scrollable（UIScrollView，UITableView，UIWebView，UICollectionView），如果scrollable的contentSize变化了，务必调用`- (void)hw_panModalSetNeedsLayoutUpdate`刷新UI！！！

**Comment by HeathWang** [comment]
注释不影响吧
