### ISSUE TITLE
present vc用navigation 包一层

### ISSUE THREAD

**Issue by steve7688** [HeathWang/HWPanModal#131]
present vc用navigation 包一层

包一层之后longFormHeight以及panScrollable似乎都只能写在自定义的UINavigationController文件上了

请问是否可以写在自定义的UINavigationController的rootviewcontroller

**Comment by HeathWang** [comment]
不能，在最初的版本是可以的，用hook的方式实现，因为造成了其他影响，后面才改成这样的
虽然丑陋了点，但问题少很多

**Comment by steve7688** [comment]
好吧 我写了一个delegate转嫁到UINavigationController的rootviewcontroller上了
