### ISSUE TITLE
'UIScrollView+Helper.h' file not found

### ISSUE THREAD

**Issue by wiilsliang** [HeathWang/HWPanModal#132]
![image](https://user-images.githubusercontent.com/22042010/201073399-b19f3c6e-4cb0-473d-8a80-d031e4799159.png)

**Comment by wiilsliang** [comment]
版本：0.9.2

**Comment by HeathWang** [comment]
我试了下没有问题，也没有类似的issue报告，请clean项目重试
或者使用最新0.9.5
