### ISSUE TITLE
App - 当在弹出控制器中添加类似今日头条的评论输入框组件后，tableview和底部组件之间会留间距

### ISSUE THREAD

**Issue by earlyfly** [HeathWang/HWPanModal#134]
![Simulator Screen Shot - iPhone 12 Pro Max - 2023-03-09 at 16 07 04](https://user-images.githubusercontent.com/19810668/223960287-c2984bbe-9dcc-44e3-9ea4-7d319f5a58ce.png)

**Comment by HeathWang** [comment]
已联系我解决，closed
