### ISSUE TITLE
presentPanModal后的控制器，添加VisualEffectView想实现虚化底部控制器view的效果无效

### ISSUE THREAD

**Issue by developer-poplar** [HeathWang/HWPanModal#135]
presentPanModal后的控制器，添加VisualEffectView想实现虚化底部控制器view的效果无效。

A控制器presentPanModal到B，B控控制器backgroundColor设为了clearColor，然后添加了VisualEffectView，想以此实现B背景为虚化后的A的效果，无效。测试系统的presentViewController可以实现

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS16.2]
 - Version [0.9]

**Comment by HeathWang** [comment]
提供的有api可以实现虚化效果，不看文档和接口？
```
#pragma mark - Background config

/**
 * use this object to config background alpha or blur effect
 * @return background config object
 */
- (HWBackgroundConfig *)backgroundConfig;
```

**Comment by developer-poplar** [comment]
你可能没理解我的意思，我不是要虚化底层控制器，而是虚化上层控制器。比如A跳转到B，我是需要虚化B

**Comment by developer-poplar** [comment]
backgroundConfig设置的是做下拉动画时底部控制器的效果。如图，我希望实现的是这样的效果。
![IMG_9345](https://user-images.githubusercontent.com/68727894/231697827-118e8d9d-3d26-4179-ae58-b7f92cbba41a.PNG)

**Comment by developer-poplar** [comment]
我已经找到了解决方案，关闭了，谢谢
