### ISSUE TITLE
请问做下滑动画时，滑动到什么位置dismiss，这个参数可以自己设置吗，我没有找到

### ISSUE THREAD

**Issue by developer-poplar** [HeathWang/HWPanModal#136]
现在默认应该是屏幕高的50%，比如我想改为80%，要修改些什么

**Comment by HeathWang** [comment]
- (void)panModalGestureRecognizer:(nonnull UIPanGestureRecognizer *)panGestureRecognizer dismissPercent:(CGFloat)percent;

判断拖动到0.8时自己调用dismiss方法

**Comment by developer-poplar** [comment]
> * (void)panModalGestureRecognizer:(nonnull UIPanGestureRecognizer *)panGestureRecognizer dismissPercent:(CGFloat)percent;
> 
> 判断拖动到0.8时自己调用dismiss方法

好的 ，非常感谢
