### ISSUE TITLE
swift 找不到  has no member 'contentShadow'

### ISSUE THREAD

**Issue by jinliyuelong** [HeathWang/HWPanModal#137]
**Describe the bug**
swift viewcontroller无法使用 contentShadow

**Screenshots**
<img width="710" alt="image" src="https://user-images.githubusercontent.com/16810284/233363251-0b3aa15e-cfcd-46c8-8f8a-5d92d7071a4e.png">

**Comment by kavinXy** [comment]
+1

**Comment by HeathWang** [comment]
请使用最新：HWPanModal 0.9.8
该问题已修复
