### ISSUE TITLE
怎么实现底部可以点击

### ISSUE THREAD

**Issue by EarthMass** [HeathWang/HWPanModal#14]
怎么实现底部可以点击

**Comment by HeathWang** [comment]
没听明白什么意思

**Comment by EarthMass** [comment]
就是弹出框底部不是有视图，可以操作，作者这种操作是present出来一个界面，那上一层的界面如果需要操作该怎么实现呢

**Comment by HeathWang** [comment]
hi，该框架的设计是类似于alert，或者全屏的present，特色在于用拖动手势来关闭弹出层，而这样做的话，底部bottom必须覆盖弹出层视图，无法满足你的目前需求。目前也没打算做事件透传。
sorry
