### ISSUE TITLE
命名问题

### ISSUE THREAD

**Issue by mlch911** [HeathWang/HWPanModal#140]
https://github.com/HeathWang/HWPanModal/blob/c907c655e5169005aa0c2058a65a6c7eebbe480f/Sources/Presentable/HWPanModalPresentationUpdateProtocol.h#L61
这里的`Swift`名称应该加个`panModal`的前缀吧，和我们这边项目里的冲突了……

**Comment by HeathWang** [comment]
好久没看issue了，不好意思

**Comment by HeathWang** [comment]
0.9.9 已发布修复
