### ISSUE TITLE
iPad窗口缩放问题

### ISSUE THREAD

**Issue by mlch911** [HeathWang/HWPanModal#149]
**Describe the bug**
在iPad上启用窗口缩放功能后，HWPanModalContentView不能跟随窗口大小一起改变，使用vc没问题

**To Reproduce**
Demo里启用窗口缩放功能，就能复现

**Expected behavior**
应该和窗口大小一起改变

**Screenshots**

https://github.com/HeathWang/HWPanModal/assets/26565394/e89a1a54-d375-4d86-b15f-215c38ec301b

**Comment by HeathWang** [comment]
HWPanModal 0.9.9
已合并mr，请使用0.9.9
