### ISSUE TITLE
我如何自己控制键盘的弹出？ 

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#16]
之前的版本我是导入了  #import "UIViewController+LayoutHelper.h" 文件， 
获取presentedVc 自己控制的， 我看现在没办法导入这个文件， 还有什么方式可以自己处理吗？

**Comment by HeathWang** [comment]
建议使用框架的自动处理。
- (BOOL)isAutoHandleKeyboardEnabled;
设置距离inputView距离 offset
- (CGFloat)keyboardOffsetFromInputView;

**Comment by fuchenxi** [comment]
keyboardOffsetFromInputView 内部计算是不是有些问题。 我设置  -textFiled.height 才刚好在输入框底部

**Comment by fuchenxi** [comment]
1. 我如果想 viewWillAppear 就弹出键盘， 页面跑到窗口最底部
2. 我点击backgroundView 收起页面时， 能否加个回调让我自己处理键盘的收起和其他一些事件

**Comment by HeathWang** [comment]
> keyboardOffsetFromInputView 内部计算是不是有些问题。 我设置 -textFiled.height 才刚好在输入框底部

offset是根据找到的inputview来的，如果不对，提供一个demo到邮箱，我排查一下

**Comment by HeathWang** [comment]
> * 我如果想 viewWillAppear 就弹出键盘， 页面跑到窗口最底部
> * 我点击backgroundView 收起页面时， 能否加个回调让我自己处理键盘的收起和其他一些事件

/**
 * 通知回调即将dismiss
 */
- (void)panModalWillDismiss;
有回调的，试试在这个回调里处理。

**Comment by fuchenxi** [comment]
1. 我如果想 viewWillAppear 就弹出键盘， 页面跑到窗口最底部

目前处理是
`
 -(void)viewWillAppear:(BOOL)animated {
    
    [super viewWillAppear:animated];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.01 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        
        [self.textField becomeFirstResponder];
    });
}
`

**Comment by HeathWang** [comment]
> 1. 我如果想 viewWillAppear 就弹出键盘， 页面跑到窗口最底部
> 
> 目前处理是
> `-(void)viewWillAppear:(BOOL)animated { [super viewWillAppear:animated]; dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.01 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{ [self.textField becomeFirstResponder]; }); }`
viewWillAppear的时候动画还在执行当中，请在viewDidAppear试试
或者后面我增加一个回调，告诉你动画已完成。

**Comment by fuchenxi** [comment]
放在viewDidAppear 键盘弹出就会有所停顿了。  类似于抖音发送评论页面

**Comment by HeathWang** [comment]
抖音的发送评论是一个单独的视图，没有嵌套到评论列表，我不知道你那边怎么做的？
你现在具体诉求是什么，把`UIViewController+LayoutHelper.h`暴露出来？

**Comment by HeathWang** [comment]
@fuchenxi 
问题解决没？
