### ISSUE TITLE
tableView不可滑动

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#17]
代理输出如下
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 11.000000
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 12.500000
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 12.500000
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 15.000000
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 16.500000
scrollViewDidScroll:] 0.000000
scrollViewDidScroll:] 17.000000
scrollViewDidScroll:] 0.000000
可能什么原因造成的？

**Comment by HeathWang** [comment]
可以提供更详细的代码吗？或者发我邮箱看看。

**Comment by fuchenxi** [comment]
使用问题：  allowsExtendedPanScrolling 返回YES， 既可滑动
