### ISSUE TITLE
如何停止用户拖拽手势滑动

### ISSUE THREAD

**Issue by JohnnyHooo** [HeathWang/HWPanModal#18]
/**
 * 是否允许pan scroll view
 * 默认为YES
 */
- (BOOL)isPanScrollEnabled;

该方法好像不生效。
目前有个界面不希望用户去滑动卡片。但是允许卡片外滑动收起。

**Comment by HeathWang** [comment]
如果你需要该方法生效，首先要返回你指定的scrollview。
```
- (nullable UIScrollView *)panScrollable;
```

**Comment by JohnnyHooo** [comment]
- (nullable UIScrollView *)panScrollable;
该方法已经return了 UIScrollView，

- (BOOL)isPanScrollEnabled;
依然不生效。

**Comment by JohnnyHooo** [comment]
场景是不希望用户可以拖动弹窗，意思就是如何关闭拖拽事件

**Comment by HeathWang** [comment]
```
/**
 * 询问delegate是否需要使拖拽手势生效
 * 若返回NO，则禁用拖拽在presented view上
 * 默认为YES
 */
- (BOOL)shouldRespondToPanModalGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer;
```
返回NO

麻烦多看看头文件文档，或者查阅demo，基本可以满足日常需求
