### ISSUE TITLE
支持下ipad

### ISSUE THREAD

**Issue by CCJ4EVER** [HeathWang/HWPanModal#19]

**Comment by HeathWang** [comment]
请问在ipad使用上有什么问题？

**Comment by CCJ4EVER** [comment]
直接崩溃，你自己可以跑一下


------------------ 原始邮件 ------------------
发件人: Heath Wang <notifications@github.com>
发送时间: 2019年7月20日 21:30
收件人: HeathWang/HWPanModal <HWPanModal@noreply.github.com>
抄送: CCJ4EVER <2810418812@qq.com>, Author <author@noreply.github.com>
主题: 回复：[HeathWang/HWPanModal] 支持下ipad (#19)




请问在ipad使用上有什么问题？

**Comment by HeathWang** [comment]
hi,
请确保`pod 'HWPanModal', '~> 0.2.9.5'`
版本在0.2.9以上，已经修复过ipad的闪退问题
