### ISSUE TITLE
Dismiss view controller when selecting table view cell

### ISSUE THREAD

**Issue by FernandoReynoso** [HeathWang/HWPanModal#20]
Hi all,
Congratulations for this amazing library!

I'm trying to integrate it in one of my personal projects but I'm having a small issue. Right now I'm presenting a view controller with a table view using the library (just like in your example project). I want to dismiss this view controller when selecting a table view cell, the view controller dismisses but for some reason this takes too much time (view controller dismisses approximately 5 seconds after selecting the cell and calling -dismissViewControllerAnimated:completion method). I did a quick test, I added a button to dismiss the view controller and it worked flawlessly, the only issue is on the table view. Also I think is important to state that I do not have any complex code running that could cause a slow performance. Am I doing something wrong? Do I need to set a more advance configuration?

Thanks!

**Comment by FernandoReynoso** [comment]
I worked!

Thanks a lot

**Comment by HeathWang** [comment]
> I worked!
> 
> Thanks a lot

You are welcome, if you like it, star it
Thanks.
