### ISSUE TITLE
tableView.contentInset问题

### ISSUE THREAD

**Issue by JohnnyHooo** [HeathWang/HWPanModal#21]
设置了tableView.contentInset.top = 100 
在向下拖拽的时候会contentInset.top会=0，导致界面异常
同时以下2个方法都试过，都不能解决问题
- (UIEdgeInsets)scrollIndicatorInsets;
{
    return UIEdgeInsetsMake(100, 0, 0, 0);
}
- (CGFloat)topOffset;
{
    return 100;
}

**Comment by HeathWang** [comment]
在viewdiload里
    self.tableView.contentOffset = CGPointMake(0, 100);
    self.tableView.contentInset = UIEdgeInsetsMake(0, 0, 44, 0);

**Comment by HeathWang** [comment]
@JohnnyHooo 
这个问题其实也不算是问题，因为设置contentInset top > 0 会使scrollView contentOffset y小于0，即触发下拉dismiss状态。
所以不建议设置contentInset top，如果你想当前状态实现类似设置top inset效果，可以：
1. 给tableView设置一定高度的tableHeaderView
2. 设置tableView section height，并提供sectionHeader

目前需要支持contentInset top生效需要较长时间修改，你可以按照上面的方案先来，谢谢。

**Comment by HeathWang** [comment]
@JohnnyHooo 
HWPanModal (0.2.9.6)已支持设置contentInset top属性。

**Comment by JohnnyHooo** [comment]
👍🏻nice！

**Comment by HeathWang** [comment]
@JohnnyHooo 
使用没问题麻烦关闭该issue，thanks

**Comment by JohnnyHooo** [comment]
貌似还是有问题，我的vc的有一个nav的。然后在未push过的情况下，拖拽会卡顿。push之后回到rootvc的时候就没问题了

**Comment by HeathWang** [comment]
> 貌似还是有问题，我的vc的有一个nav的。然后在未push过的情况下，拖拽会卡顿。push之后回到rootvc的时候就没问题了

麻烦参考一下demo，还不能解决发我邮箱我看看

**Comment by JohnnyHooo** [comment]
已经解决了，👍！
