### ISSUE TITLE
遇到了2个问题

### ISSUE THREAD

**Issue by JohnnyHooo** [HeathWang/HWPanModal#23]
问题1：聊天界面创建几条消息cell的时候，tableview scrollToRowAtIndexPath无法进行滑动
问题2：设置了panScrollable之后，拖拽panScrollable区域以外无法收起弹窗。如：头部标题View

**Comment by HeathWang** [comment]
问题1还是需要给demo我看看
问题2，你的头部标题View不是添加到scrollable上的？

**Comment by JohnnyHooo** [comment]
demo已经做好了，已发送至你的邮箱~

**Comment by JohnnyHooo** [comment]
目前问题已得到解决，感谢大大👍

问题1可这样解决：
每次改变 scrollable.contentSize 都调用 [self hw_panModalSetNeedsLayoutUpdate];

问题2可这样解决：
- (BOOL)shouldPrioritizePanModalGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer {
    CGPoint loc = [panGestureRecognizer locationInView:self.view];
    if (CGRectContainsPoint(self.topView.frame, loc)) {
        return YES;
    }
    
    return NO;
}
