### ISSUE TITLE
longFormHeight/shortFormHeight

### ISSUE THREAD

**Issue by ritchie7** [HeathWang/HWPanModal#24]
- (PanModalHeight)longFormHeight {
    CGFloat h = (FBXSafeAreaBottom()+kWINDOW_H/5*3);
    PanModalHeight height = PanModalHeightMake(PanModalHeightTypeContent, h);
    return height;
}

当 h 为 float 类型时，会出现滑动 contentView 就 dismiss 的问题
将 h 类型改为 integer 时，该问题消失

**Comment by HeathWang** [comment]
你好，我实际测试没有这个问题，请提供较完整的配置信息。

**Comment by HeathWang** [comment]
@ritchie7 
HWPanModal (0.3.2.1)
已修复该问题，由于float进度问题造成，目前精度控制在0.0001范围内
