### ISSUE TITLE
能否移出掉关于KVOController的依赖

### ISSUE THREAD

**Issue by JohnYuGit** [HeathWang/HWPanModal#26]
**Describe the bug**
已实现部分的功能引入到pod当中，能不能通过原生的实现KVOController的相关依赖。

**Comment by HeathWang** [comment]
引入KVOController是有什么问题吗？

**Comment by JohnYuGit** [comment]
项目中已经引入基本完全实现的相关的功能模块，且深度依赖。我看到对于KVOController的代码并不是很多，可以考虑单独实现部分。

**Comment by HeathWang** [comment]
后面迭代我看看去除依赖，对您现在的开发影响大吗？

**Comment by JohnYuGit** [comment]
目前还好，只是建议。担心会和别人魔改项目冲突导致不太好。

**Comment by HeathWang** [comment]
@JohnYuGit 
`HWPanModal (0.4.1) successfully published`
已移除对KVOController的依赖。
