### ISSUE TITLE
影响iOS13 present modalPresentationStyle

### ISSUE THREAD

**Issue by CivelXu** [HeathWang/HWPanModal#27]
具体bugs：
在iOS13中 present 带Navigation的控制器， 设置 nav.modalPresentationStyle = .fullScreen 无效， present的效果依旧是iOS13中的pageSheet效果
定位问题到 UINavigationController+HWPanModal.m 文件中
[self hw_swizzleInstanceMethod:@selector(pushViewController:animated:) with:@selector(hw_pushViewController:animated:)];

**Comment by HeathWang** [comment]
好的，我去检查一下

**Comment by HeathWang** [comment]
@CivelXu 
HWPanModal (0.3.6)
已修复iOS13上modalPresentationStyle失效问题，麻烦看看问题解决没。

**Comment by CivelXu** [comment]
@HeathWang 可以了 这种方法交换出了问题 工程里面很难排查

**Comment by HeathWang** [comment]
> @HeathWang 可以了 这种方法交换出了问题 工程里面很难排查

不是交换的问题，是在controller没有present出来的时候调用了获取`presentationController `造成的。
