### ISSUE TITLE
edge返回手势冲突

### ISSUE THREAD

**Issue by gongqiuwei** [HeathWang/HWPanModal#28]
0.3.6版本，当present一个uinavigationcontroller， 如何处理hwpancontainerView的edge返回手势与自己的uinavigationcontroller的全屏返回手势的冲突？？

**Comment by HeathWang** [comment]
`- (BOOL)allowScreenEdgeInteractive;`
默认这个是关闭的，应该不会影响到这个手势，请更新到0.4.0版本看看。

**Comment by gongqiuwei** [comment]
额，需求是这样的，我利用hw框架present一个navigation出来，首先，在hw的页面需要下拉dismiss，也需要左滑dismiss，然后navigation导航到其他页面，有自己的pop返回手势，总体需求就是这样的，类似头条的评论详情页弹窗。现在比较头疼的是，看源码发现edge手势起作用的话，navigation的pop手势就失效了，所以能不能后期增加一些处理，对这个方面，现在我的做法是在源码增加一个代理方法gestureRecognizerShouldBegin，用于判定edge是否开启。这个处理不太好，希望大神能后期增加这个需求处理。。还有edge如何全屏起作用，我觉得也是用这个框架的时候经常需要的，个人想法，仅供参考。

**Comment by HeathWang** [comment]
@gongqiuwei 
全屏侧滑返回有好几人提到，目前没有好的思路做成什么样的交互形式，比如是直接侧滑就全部dismiss掉，还是先把navigationController栈中的controller全部pop出来再dismiss。

你的这个手势问题倒是可以先沟通改进。
具体可以给我发邮件，互通联系方式来解决，issue很难说清楚。

**Comment by HeathWang** [comment]
@gongqiuwei 
`0.4.2`已支持全屏侧滑返回手势，当处于nav 栈的root，该手势生效。

**Comment by gongqiuwei** [comment]
sorry,暂时无法测试，demo试了下可行，自己集成的还没弄
