### ISSUE TITLE
如果同时弹出两个视图，有没有好的解决方案？

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#3]
Attempt to present <HWAlertViewController: 0x1049330a0>  on <HWViewController: 0x104c0bfb0> which is already presenting (null)
你的demo里 alert ， 我尝试连续弹两个， 会出现上述提示， 能不能处理一下两个alertView 或者presentVC 同时存在， 不知有什么好点的解决方案没

**Comment by HeathWang** [comment]
@fuchenxi 
目前是这样的，因为pop是内部用到了UIPresentationController，UIPresentationController会保证当前Controller present的对象只存在一个。

如果你想要弹出浮层，然后浮层上再弹出浮层，可以这样做：
在第一个弹出的浮层上继续present Controller即可
`
@interface HWStackedGroupViewController () <HWPanModalPresentable>

@end

@implementation HWStackedGroupViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}

#pragma mark - tableView delegate

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    UIColor *color = [self colorWithIndex:indexPath.row];
    HWColorDetailViewController *controller = [HWColorDetailViewController new];
    controller.color = color;
    [self presentPanModal:controller];
}

#pragma mark - HWPanModalPresentable


- (PanModalHeight)longFormHeight {
    return PanModalHeightMake(PanModalHeightTypeMax, 0);
}

- (PanModalHeight)shortFormHeight {
    return [self longFormHeight];
}

@end
`
