### ISSUE TITLE
知乎评论这个效果里,如果点击用户头像,可以像知乎那样直接push到用户个人信息页吗?

### ISSUE THREAD

**Issue by zhangEnBin1010** [HeathWang/HWPanModal#30]
知乎评论这个效果里,如果点击用户头像,可以像知乎那样直接push到用户个人信息页吗?

**Comment by HeathWang** [comment]
目前可以做到在同一个navigation栈里push，至于你要做的一模一样，可以要花时间调整UI。

**Comment by zhangEnBin1010** [comment]
好的 我又重新自定义个导航栏和自定义转场动画解决了

**Comment by zhangEnBin1010** [comment]
我在第一个vc push到下个vc 两个VC都有tableview,第二个vc也遵循了- (nullable UIScrollView *)panScrollable;协议 但是下拉的时候 第二个vc的tableview也跟着滚动,可以帮我看下什么问题吗

**Comment by HeathWang** [comment]
你push到第二个，第二个vc的tableView跟着滚动不是正确的逻辑吗？
没明白你要怎么做

**Comment by HeathWang** [comment]
@zhangEnBin1010 我测试了一下，push到一个有scrollable的VC，是可以正常滑动dismiss的
可以提供一个简单的demo发我邮箱，我看看具体问题，谢谢。

**Comment by zhangEnBin1010** [comment]
@HeathWang 已发送到邮箱 帮忙看下 谢谢

**Comment by HeathWang** [comment]
### 重要
如果present一个navigationVC，并且每个子vc都有scrollView视图，该scrollView必须使用**懒加载**或者在`- (void)viewDidLoad;` or `- (void)viewDidAppear:(BOOL)animated;`方法中调用`[self.navigationController hw_panModalSetNeedsLayoutUpdate];`以确保交互正常。

**Comment by ddongdong521** [comment]
> 好的 我又重新自定义个导航栏和自定义转场动画解决了



> 好的 我又重新自定义个导航栏和自定义转场动画解决了

您好,请问这里是怎么做的 可以给我一份demo吗 谢谢啦 我邮箱595888098@qq.com

**Comment by haofanning** [comment]
https://github.com/HeathWang/HWPanModal/issues/30#issuecomment-544798178 试了不行啊
