### ISSUE TITLE
可以加个在顶部设置阴影的属性吗？

### ISSUE THREAD

**Issue by lixiangshadow** [HeathWang/HWPanModal#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
具体指的是indicator指示器下面，可配置圆角的那个view吗？

**Comment by HeathWang** [comment]
`HWPanModal (0.6.1) successfully published`
已支持添加阴影配置，任何疑问，请联系我
