### ISSUE TITLE
present 带导航的bug

### ISSUE THREAD

**Issue by CivelXu** [HeathWang/HWPanModal#32]
Group-Nav-知乎评论能复现bug
操作流程
1. 点击 App Demo，
2. 点击 Group-Nav-知乎评论
3. 下滑关闭界面， 可见界面消失， 然后离开上滑界面， 原界面可以继续弹出。

**Comment by HeathWang** [comment]
我这边测试正常，如果需要dismiss弹出层，你需要

1. 慢速拖动到至少屏幕y轴中间以下
2. 以极快速的拖动

现有交互并不是你开始拖动就关闭弹出层视图。

**Comment by CivelXu** [comment]
demo 中的问题是存在的 。
带导航的那种 Group—Nav， PresentingViewControllerAnimationStyle 为 pageSheet
向下拖动 弹出层消失后， 立刻手往上拖动会把弹出层再次拉回来。
有可能是消失的动画还没有完成 ，我的意思是这里可以考虑优化一下。

**Comment by HeathWang** [comment]
我试了下，确实可以复现，刚开始没理解您的意思。
感谢，我修复一下。
@CivelXu

**Comment by HeathWang** [comment]
@CivelXu 
已修复on `0.6.4`，麻烦看看修复没

**Comment by CivelXu** [comment]
上滑呼出弹窗层的问题解决了。
这种界面还有一个问题是，下滑弹出层消失之后，底下的界面会短时间内无法触摸，原因应该是控制导航转场的dismiss动画还没有完全结束。如果缩短 转场动画会得到解决 但是动画效果就没有理想了。

**Comment by HeathWang** [comment]
微信也有类似的问题，比如侧滑把网页最小化，有短暂无法触摸的问题。
你可以把animation duration缩短，然后animation options不用spring，应该会好一点。

**Comment by CivelXu** [comment]
能否考虑把 transitionDuration 开始和结束的时间 分开给接口； 缩短结束的动画时间时候？如果缩短开始的时候动画效果很不好， 可以看一下今日头条的评论弹出层， 不会感受到无法触摸的情况。

**Comment by CivelXu** [comment]
```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        duration = 0.2
    }
```
动态更改了duration， 可以修改 无法触摸的情况

**Comment by HeathWang** [comment]
> ```
>     override func viewDidAppear(_ animated: Bool) {
>         super.viewDidAppear(animated)
>         duration = 0.2
>     }
> ```
> 
> 
> 动态更改了duration， 可以修改 无法触摸的情况

可以，后面考虑加上

**Comment by HeathWang** [comment]
@CivelXu HWPanModal (0.6.5)
`- (NSTimeInterval)dismissalDuration;`
