### ISSUE TITLE
使用HWPanModalContentView的时候怎么关闭ViewController的侧滑返回

### ISSUE THREAD

**Issue by evan-lei** [HeathWang/HWPanModal#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
这个需要你自己关闭去控制
比较简单的是使用[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture)

**Comment by evan-lei** [comment]
> 这个需要你自己关闭去控制
> 比较简单的是使用[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture)

thanks
