### ISSUE TITLE
Content misplacement on iPhone X when PanModalHeight is set to intrinsic

### ISSUE THREAD

**Issue by Sega-Zero** [HeathWang/HWPanModal#34]
**Describe the bug**
If I set the bottom content constraint to safe area (rather than superview, in that case everything works fine) and return `PanModalHeight(type: .intrinsic, height: 0)` for `longFormHeight`, I am able to drag the content up higher, leaving the gap at the bottom (which seems to be equal to safeAreaInsets.bottom). 

**To Reproduce**
1. Patch `ShoppingCartViewController` with these changes:
```swift
        bgView.snp.makeConstraints { (maker) in
//            maker.edges.equalTo(view)
            maker.leading.equalToSuperview()
            maker.trailing.equalToSuperview()
            maker.top.equalToSuperview()
            if #available(iOS 11.0, *) {
                maker.bottom.equalTo(self.view.safeAreaLayoutGuide)
            } else {
                maker.bottom.equalToSuperview()
            }
        }

...

extension ShoppingCartViewController {

    override func longFormHeight() -> PanModalHeight {
        return PanModalHeight(type: .intrinsic, height: 0)
    }
```

2. Present the viewcontroller
3. Drag it higher

**Expected behavior**
Just like in `.content` mode, I expect the viewcontroller will not move higher that it's intrinsic content size.

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-11-24 at 23 44 18](https://user-images.githubusercontent.com/2203199/69501265-5fd86080-0f14-11ea-9d0c-a9c008fd6485.png)
<details>
  <summary>Screencast</summary>

![ezgif-1-bcdee9e60ccd](https://user-images.githubusercontent.com/2203199/69501311-d5dcc780-0f14-11ea-9823-7e3cb1c18716.gif)

</details>

**Comment by HeathWang** [comment]
hi, Sega-Zero
What version do you use `HWPanModal`
The latest version is 0.6.5
I use your code, and testing, it seems correct.

**Comment by Sega-Zero** [comment]
Caught that on 0.6.4. Made a retest on 0.6.5 and reproduce the very same behaviour.
The bug is a bit tricky, somehow I catch this only on first present of `ShoppingCartViewController` and only if I drag it up first, without dragging down

<details>
<summary>ScreenShot</summary>

![ShoppingCartController swift — Edited 2019-11-26 14-42-31](https://user-images.githubusercontent.com/2203199/69627248-5574ae80-105b-11ea-972c-0b334fc0fe22.jpg)

</details>

**Comment by HeathWang** [comment]
@Sega-Zero 
yeah, I have reproduced this bug. just happened first time.
Strange.
Give me some time to fix it.

Current solution:
Do NOT use `intrinsic`， you should calculate height by yourself.

Thank you.

**Comment by HeathWang** [comment]
@Sega-Zero 
hey guys, I'm busy on my work, sorry for there is no time to fix it.
I will fix it as soon as I have time to do.
