### ISSUE TITLE
点击其他按钮手动dismiss怎么弄?

### ISSUE THREAD

**Issue by lixiangshadow** [HeathWang/HWPanModal#35]
点击其他按钮手动dismiss怎么弄?

**Comment by HeathWang** [comment]
可以看下demo里有相关示例：
如果是UIViewController，直接调用`- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion;`

如果使用的是`HWPanModalContentView`，调用`- (void)dismissAnimated:(BOOL)flag completion:(void (^)(void))completion;`

**Comment by lixiangshadow** [comment]
知道了,谢谢
