### ISSUE TITLE
你好,我想在tabbar的上方弹出,tabbar的item还需要能点击,有什么方法能实现?急,谢谢

### ISSUE THREAD

**Issue by lixiangshadow** [HeathWang/HWPanModal#36]
你好,我想在tabbar的上方弹出,tabbar的item还需要能点击,有什么方法能实现?急,谢谢

**Comment by HeathWang** [comment]
hi,
你可以尝试使用`HWPanModalContentView`，这个类继承自UIView，实现了controller相似的交互
