### ISSUE TITLE
HWPanModal在iOS13以下会对TabBarController的导航控制器强引用

### ISSUE THREAD

**Issue by Zomfice** [HeathWang/HWPanModal#37]
发现在iOS13以上，导入HWPanModal 进行RootController切换，Tab的导航控制器能够正常释放，但在iOS13以下，会对导航控制器强引用
![image](https://user-images.githubusercontent.com/19898945/70200797-98b3d900-174f-11ea-98d2-96efbe6051d2.png)
![image](https://user-images.githubusercontent.com/19898945/70202440-a750bf00-1754-11ea-9dcc-2ac98b886b78.png)
发现是presentationController 这个类导致的循环引用问题
UIViewController.presentationController.delegate 的 delegate 在 iOS 13 之前的声明是 strong 的，导致 delegate 的两端相互强引用无法正常释放，苹果在 iOS 13 悄咪咪地改为了 weak，但对于 iOS 12 及之前的版本这个内存泄漏问题则会一直存在

**Comment by HeathWang** [comment]
好issue，我去看看怎么搞
👍

**Comment by HeathWang** [comment]
可以来个merge request❤️

**Comment by HeathWang** [comment]
```
- (void)dismissalTransitionDidEnd:(BOOL)completed {
	if (completed) {
		// break the delegate
		self.delegate = nil;
	}
}
```
已修复部分问题，还有你修改的部分，请更新到0.6.6版本看看

**Comment by Zomfice** [comment]
好的
