### ISSUE TITLE
希望能给一个仿知乎的评论全屏跳转到个人信息页的解决方案

### ISSUE THREAD

**Issue by ddongdong521** [HeathWang/HWPanModal#38]
我自己自定义的 push 没法实现全屏 push，希望能给一个解决方案。谢谢

**Comment by HeathWang** [comment]
https://github.com/HeathWang/HWPanModal/issues/30
push到下一层的时候，直接把view的frame设置成全屏不生效吗？我没有具体实践过。

**Comment by HeathWang** [comment]
你如果只是单层的显示浮层弹框，不像知乎那样点“查看回复”还有一层，可以使用`HWPanModalContainerView`直接弹出view，这样不影响你的视图栈，然后点击用户头像在push就是全屏的。

**Comment by ddongdong521** [comment]
> 你如果只是单层的显示浮层弹框，不像知乎那样点“查看回复”还有一层，可以使用`HWPanModalContainerView`直接弹出view，这样不影响你的视图栈，然后点击用户头像在push就是全屏的。

我们这个评论就是全都仿照知乎做的,所以没用一个view做

**Comment by ddongdong521** [comment]
> 你如果只是单层的显示浮层弹框，不像知乎那样点“查看回复”还有一层，可以使用`HWPanModalContainerView`直接弹出view，这样不影响你的视图栈，然后点击用户头像在push就是全屏的。

我们这个评论就是全都仿照知乎做的,所以没用一个view做

**Comment by ddongdong521** [comment]
我现在的实现方案是用present 使用的push动画,但是这样有个问题就是,我们在评论中可能会跳转的页面比较多,很多页面之前都是push进入的,导致返回按钮的点击事件可能要重写好多

**Comment by HeathWang** [comment]
> 我现在的实现方案是用present 使用的push动画,但是这样有个问题就是,我们在评论中可能会跳转的页面比较多,很多页面之前都是push进入的,导致返回按钮的点击事件可能要重写好多

这个不失是个好的办法，你们的navigationBar是自定义view还是系统的？
我再尝试用自定义navBarView解决你的问题

**Comment by HeathWang** [comment]
@ddongdong521 
我已经把相关示例push到master分支，请拉取最新代码，参考``知乎评论`那个例子。

**Comment by ddongdong521** [comment]
好的 谢谢啦
