### ISSUE TITLE
闪退，或有时卡住划不动

### ISSUE THREAD

**Issue by ilumanxi** [HeathWang/HWPanModal#39]
![30701576737704_ pic_hd](https://user-images.githubusercontent.com/11832459/71151035-dfd0bc80-226d-11ea-9b87-436116a83a45.jpg)

**Comment by HeathWang** [comment]
机型，OS版本，重现步骤？

**Comment by ilumanxi** [comment]
iPhone XS iOS  13.3 ， 当UITableView中Cell很少，向上快速滑动

**Comment by HeathWang** [comment]
hi，我试了无法重现，可以提供一个小demo让我调试一下吗？
