### ISSUE TITLE
HWGroupViewController 如果给tableView的contentOffset一个初始值，滑动时偏移量先归零了

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#4]

**Comment by fuchenxi** [comment]
`- (void)didPanOnScrollView:(UIScrollView *)scrollView change:(NSDictionary<NSKeyValueChangeKey, id> *)change {

	if (!self.presentedViewController.isBeingDismissed && !self.presentedViewController.isBeingPresented) {

		if (!self.isPresentedViewAnchored && scrollView.contentOffset.y > 0) {
			[self haltScrolling:scrollView];
		} else if ([scrollView isScrolling] || self.isPresentedViewAnimating) {
`
if (!self.isPresentedViewAnchored && scrollView.contentOffset.y > 0) 这个判断是否可以优化下

**Comment by HeathWang** [comment]
不清楚实际的需求点，目前依赖contentOffset来实现拖拽效果
可以尝试去设置`@property(nonatomic) UIEdgeInsets contentInset;`

**Comment by fuchenxi** [comment]
比如弹出一个单选列表， 弹出后 我希望默认选中第十个cell， 并且把它滚动到可视的位置。 
比如' scrollToIndex:10 '。 此时如果我滑动列表， 内部判断会先把scrollView的contentOffset.y设置为0

**Comment by HeathWang** [comment]
> 比如弹出一个单选列表， 弹出后 我希望默认选中第十个cell， 并且把它滚动到可视的位置。
> 比如' scrollToIndex:10 '。 此时如果我滑动列表， 内部判断会先把scrollView的contentOffset.y设置为0

了解，下一版修复，谢谢

**Comment by HeathWang** [comment]
@fuchenxi 
该问题已修复，pod版本0.2.6.1

**Comment by fuchenxi** [comment]
好的， 我试下
