### ISSUE TITLE
HWPanModel 显示之后会添加约束给UIWindow和UILayoutContainView,这会导致问题

### ISSUE THREAD

**Issue by Zomfice** [HeathWang/HWPanModal#40]
在没有显示HWPanModel的时候,这是正常的
![WX20191220-122658](https://user-images.githubusercontent.com/19898945/71230407-7b246900-2324-11ea-8d98-d6bec33b1e43.png)
在显示HWPanModel的之后,这样会导致我在切换选中TabController的时候，直接修改了我NavigationController的高度,导致Controller异常
![WX20191220-122749](https://user-images.githubusercontent.com/19898945/71230425-8e373900-2324-11ea-9485-9551810fd657.png)

**Comment by HeathWang** [comment]
PanModal是present出来的，你为什么还可以操作TabController？

**Comment by Zomfice** [comment]
比如我在第三个Tab有一个弹出PanModal的功能，我点击弹出PanModal，然后点击第一个Tab跳转到第三个Tab的时候，这时候已经给Window和UILayoutContainerView添加了约束，在iOS13以下就会导致NavigationController的高度改变

**Comment by Zomfice** [comment]
弄了一个小Demo，操作步骤在AppDelegate里面，有时间看一下，谢谢
[Demo.zip](https://github.com/HeathWang/HWPanModal/files/3994973/Demo.zip)

**Comment by HeathWang** [comment]
请不要在present的时候改变栈或者视图，类似于系统的UIAlertController，你应该把PanModal先dismiss掉，然后再做后续操作。本身我的代码没有改变约束，都是依据系统的api做了相关的转场动画。

如果你实在有这样的交互需求，可以使用`HWPanModalContainerView`，这个类实现了和Controller相似的操作，唯一不同的是，它是个view加到Controller的视图上。

**Comment by Zomfice** [comment]
操作是在panModel dimiss完成之后，然后切换到其他页面做的栈或者跳转操作

**Comment by HeathWang** [comment]
> 操作是在panModel dimiss完成之后，然后切换到其他页面做的栈或者跳转操作

hi, 为什么我下载下来运行是好的，方便的话微信交流
你的联系邮箱？
