### ISSUE TITLE
HWPanModalContentView 弹出 collectionView 做横向滚动时滑动有问题

### ISSUE THREAD

**Issue by WonderJeffy** [HeathWang/HWPanModal#42]
**Describe the bug**
1、已在 reloadData 之后调用了 hw_panModalSetNeedsLayoutUpdate 
2、竖向滚动没有问题
3、设置为横向后 flowLayout 的 inset 设置不准，右滑会让 collectionView 归位到 0，左滑很难触发

我注意到，滑动触发的方法 HWPanModalPresentableHandler.m
- (void)didPanOnScrollViewChanged:(NSDictionary<NSKeyValueChangeKey, id> *)change；
里面只判断了 scrollView.contentOffset.y > 0 

另外，正常竖向滚动触发 trackScrolling
而横向滚动 总是触发 haltScrolling

**Comment by HeathWang** [comment]
测试时没测过横向滚动问题，可以把collectionView初始化和配置贴出来吗？

**Comment by WonderJeffy** [comment]
> 测试时没测过横向滚动问题，可以把collectionView初始化和配置贴出来吗？

**复现场景是在 一个已经 panmodal 弹出的竖向滚动 VC 上再弹出一个横向滚动的 HWPanModalContentView**

collectionView 如下：
```
- (UICollectionView *)collectionView {
    if (!_collectionView) {
        UICollectionViewFlowLayout *layout = [[UICollectionViewFlowLayout alloc] init];
        layout.minimumLineSpacing      = 10;
        layout.minimumInteritemSpacing = 10;
        layout.scrollDirection = UICollectionViewScrollDirectionHorizontal;
        layout.itemSize        = CGSizeMake(100, 100);
        layout.sectionInset    = UIEdgeInsetsMake(0, 20, 0, 20);
        
        _collectionView = [[UICollectionView alloc] initWithFrame:CGRectMake(0, 0, kScreenWidth, 100) collectionViewLayout:layout];
        _collectionView.showsHorizontalScrollIndicator = NO;
        [_collectionView registerClass:[XYCollectionViewCell class] forCellWithReuseIdentifier:@"XYCollectionViewCell"];
        _collectionView.delegate = self;
        _collectionView.dataSource = self;
    }
    return _collectionView;
}
```

**Comment by HeathWang** [comment]
无法复现你的问题，我在master分支加了一个新类`HWCollectionPanModalView`
你可以拉最新的代码看看，如何复现，把修改贴出来，谢谢。

**Comment by HeathWang** [comment]
@WonderJeffy 
当CollectionView横向滚动时，和该框架原有交互设计下滑scrollView dismiss视图相冲突。

你可以重写该方法，返回nil：
```
- (UIScrollView *)panScrollable {
    return nil;
}
```
