### ISSUE TITLE
UIDatePicker 使用问题？？？

### ISSUE THREAD

**Issue by difoi** [HeathWang/HWPanModal#44]
使用UITableView 滑动没有问题。
但是使用UIDatePicker,弹出和显示都没有问题;向下滑动时间选择时，会自动下滑关闭窗口，请问怎么解决？？？

    override func longFormHeight() -> PanModalHeight {
        return PanModalHeight(type: .contentIgnoringSafeArea, height: 380.0)
    }

    override func anchorModalToLongForm() -> Bool {
        return true
    }

   override func panScrollable() -> UIScrollView? {
        return nil
    }

**Comment by HeathWang** [comment]
```
- (BOOL)shouldRespondToPanModalGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer {
    CGPoint loc = [panGestureRecognizer locationInView:self.view];
    return !CGRectContainsPoint(self.datePicker.frame, loc);

}
```
重写该方法，判断panGestureRecognizer location是否在dataPicker中。

**Comment by HeathWang** [comment]
或者最简单
```
- (BOOL)allowsDragToDismiss;
```
返回NO

**Comment by difoi** [comment]
非常感谢，重写 shouldRespond 就可以了

**Comment by northcity** [comment]
非常棒，解决了我的问题。作者大大真厉害！
