### ISSUE TITLE
如果前面vc隐藏导航栏 模态之后在返回的的话 导航栏会跳动

### ISSUE THREAD

**Issue by miaojia** [HeathWang/HWPanModal#48]
MJMineGiftListViewController *list=[[MJMineGiftListViewController alloc]init];
[self presentPanModal:list];

[list dismissViewControllerAnimated:NO completion:nil];

**Comment by HeathWang** [comment]
请提供更详细的代码，包含隐藏，show 导航栏操作。

**Comment by miaojia** [comment]
前面aVC隐藏导航栏代码
-(void)viewWillAppear:(BOOL)animated{

    [super viewWillAppear:animated];
    self.navigationController.navigationBar.hidden=YES;

}
-(void)viewDidAppear:(BOOL)animated{

    [super viewDidAppear:animated];
    self.navigationController.navigationBar.hidden=YES;
}

-(void)viewWillDisappear:(BOOL)animated{
    [super viewWillAppear:animated];

    self.navigationController.navigationBar.hidden=NO;
}
push需要模态操作的bVC
-(void)viewWillAppear:(BOOL)animated{
    
    [super viewWillAppear:animated];
    self.navigationController.navigationBar.hidden=NO;
}

-(void)viewDidAppear:(BOOL)animated{
    
    [super viewDidAppear:animated];
    self.navigationController.navigationBar.hidden=NO;
    
}
bVC中按钮点击、弹出模态
MJMineGiftListViewController *list=[[MJMineGiftListViewController alloc]init];
[self presentPanModal:list];
list中接口请求成功后，操作[list dismissViewControllerAnimated:NO completion:nil];
隐藏的导航栏出现

**Comment by yzm347404** [comment]
确实会，今天我也遇到了，不过我把self.navigationController.navigationBar.hidden=YES;放到viewdidload就好了，可能业务不一样哈，希望对你有用

**Comment by HeathWang** [comment]
@miaojia 
框架内部调用的也是present操作，你可以试试present出来一个VC，然后调用di什么issViewControllerAnimated，看看有没有nav bar跳动的问题。

**Comment by miaojia** [comment]
我不太理解你的意思，是不要push需要模态操作的vc，改用模态的vc操作？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Heath Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 晚上9:52
收件人:&nbsp;"HeathWang/HWPanModal"<HWPanModal@noreply.github.com&gt;;
抄送:&nbsp;"小蛋仔"<824610487@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HeathWang/HWPanModal] 如果前面vc隐藏导航栏 模态之后在返回的的话 导航栏会跳动 (#48)





 
@miaojia
 框架内部调用的也是present操作，你可以试试present出来一个VC，然后调用di什么issViewControllerAnimated，看看有没有nav bar跳动的问题。

**Comment by HeathWang** [comment]
我的意思是你看你正常present一个controller，然后dismiss，会不会有这个现象

**Comment by Kejiasir** [comment]
刚好写了个重现 #53  bug 的 demo，里面有涉及到导航栏的隐藏显示，你看看这部分逻辑跟你的需求场景符不符合，可以参考下。
[TestDemo.zip](https://github.com/HeathWang/HWPanModal/files/4537142/TestDemo.zip)

**Comment by HeathWang** [comment]
@miaojia 你的问题解决没
