### ISSUE TITLE
presentPanModal: modal 一个导航控制器问题

### ISSUE THREAD

**Issue by Kejiasir** [HeathWang/HWPanModal#49]
你好，我通过`presentPanModal:`方法，modal 一个导航控制器，然后在`viewWillAppear:`的时候隐藏导航栏，拖拽关闭的时候不能 dismiss 整个控制器，并且设置 `shortFormHeight` 无效，一出来就直接到顶部了。

**Comment by HeathWang** [comment]
请优先阅读markdown和example里的示例。
或者贴出你具体的实现代码

**Comment by Kejiasir** [comment]
😃解决了，谢谢回复

**Comment by Kejiasir** [comment]
另外一个问题，请问顶部圆角`cornerRadius`可以动态修改吗，比如我想在 状态为`PresentationStateLong`的时候设置为 0，回到`PresentationStateShort`的时候再动态调整回 10，我还没看到有方法可以动态设置

**Comment by HeathWang** [comment]
UIViewController+Presentation.h
`- (void)hw_panModalSetNeedsLayoutUpdate`
调用这个可以刷新UI配置，然后你可以修改圆角
```
- (CGFloat)cornerRadius {
    // 根据不同情况返回不同圆角
    return xyz;
}
```

**Comment by Kejiasir** [comment]
🤣好的，谢谢，刚刚想说试了`hw_panModalSetNeedsLayoutUpdate`的方法，没有效果，不会触发 layout update

**Comment by HeathWang** [comment]
写漏了，后面加上

Arvin <notifications@github.com> 于2020年4月17日周五 下午5:27写道：

**Comment by Kejiasir** [comment]
好的，谢谢
