### ISSUE TITLE
集成极光统计导致crash

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#50]
![image](https://user-images.githubusercontent.com/24308071/79817693-a3969f80-83b8-11ea-9e47-98bcf8bf1e86.png)
![image](https://user-images.githubusercontent.com/24308071/79817726-b1e4bb80-83b8-11ea-92dc-25d1fa56bbf4.png)

发生在统计开始时
| JIGUANG | D - [JIGUANGRequestSession] setViewStart name CXYStoreDetails_VC time 2020-04-21-10:14:23

崩溃处打印
(lldb) po self
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
0x0000000117f459b0

我们App新增的需求添加极光统计， 未添加时一切正常， 商品详情和店铺都有分享
操作顺序  打开店铺分享 ->  关闭店铺分享 -> 打开商品分享 -> crash
操作顺序  打开商品分享 ->  关闭商品分享 -> 打开店铺分享 -> crash

**Comment by HeathWang** [comment]
难道是runtime方法冲突造成的？单独看这个看不出来。

**Comment by fuchenxi** [comment]
我把极光给去了， 换成了友盟， 感觉像是被hook了， 测试发现有五六个页面莫名其妙的闪退， 还有的闪退在main函数。
