### ISSUE TITLE
vc里面添加tableview，使用协议的panscrolable返回，但是不能滑动，这是怎么回事呢

### ISSUE THREAD

**Issue by yzm347404** [HeathWang/HWPanModal#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
show me your code.

**Comment by yzm347404** [comment]
我已经解决了，老哥，
![image](https://user-images.githubusercontent.com/15798109/79973866-e2b51580-84ca-11ea-88d2-f2d8fa1f2a03.png)

**Comment by yzm347404** [comment]
感觉跟方法调用的前后有关，如果tb没有数据就调用了这个代理的方法，那么content.size.height是==0的，那么，后期数据回来刷新了数据，实际的content.size.height不为0了，但是里面走的结果是content.size.height==0的结果，然后tb就不能滑动了，应该是这样

**Comment by HeathWang** [comment]
@yzm347404 
如果你scrollview数据发生变化导致contentSize变化，需要reloadLayout，这个md上写。

```
- (void)hw_panModalSetNeedsLayoutUpdate;
```

**Comment by yzm347404** [comment]
难怪，哈哈，我那样写死那个方法也可以，你认为呢

发自我的 iPhone
