### ISSUE TITLE
你好，请问有办法在 "PresentationStateShort" 状态下 push 一个全屏的控制器吗

### ISSUE THREAD

**Issue by Kejiasir** [HeathWang/HWPanModal#52]
我现在通过`presentPanModal:`方法弹出一个导航控制器，默认状态是`PresentationStateShort`，在该控制器中有业务需要 push 一个新的控制器，请问有方案可以做到吗？目前 push 出来的控制器的状态还是`PresentationStateShort`。

**Comment by HeathWang** [comment]
可以下载项目example下来，知乎评论那个例子和你要的需求比较类似，在push到新的VC时，可以改变short-> long.
`HWNavViewController`

**Comment by Kejiasir** [comment]
谢谢大佬，看到了，😂请问上次那个动态修改圆角的加了吗

**Comment by HeathWang** [comment]
项目太忙，那个改动有点多，还没弄

**Comment by Kejiasir** [comment]
好的好的，了解，谢谢大佬

**Comment by HeathWang** [comment]
> 谢谢大佬，看到了，😂请问上次那个动态修改圆角的加了吗

 🚀  HWPanModal (0.7.1) successfully published
 📅  April 24th, 04:34
 🌎  https://cocoapods.org/pods/HWPanModal
 👍  Tell your friends!

@Kejiasir
