### ISSUE TITLE
你好，发现一个很严重的问题

### ISSUE THREAD

**Issue by Kejiasir** [HeathWang/HWPanModal#53]
modal 出来的导航控制器，里面包含一个 collectionview，数据源有很多，在当前控制器自由的切换 short 和 long 状态是没有一点问题，再push 一个控制器后（pop回来）也没有问题。

但是如果刷新 collectionview 的数据源，collectionview只有几个数据的时候，push 一个控制器问题就来了，整个导航控制器（包括 push 出来的控制器）的高度变了，再也回不到 long 的状态，感觉整个导航控制器的高度就是跟里面的 collectionview 的数据源绑定了？

[video.zip](https://github.com/HeathWang/HWPanModal/files/4532255/video.zip)
我录制了一个具体操作的小视频，还请麻烦大佬看一下。

**Comment by HeathWang** [comment]
可以写个小demo来完整复现吗？这问题确实有点严重。

**Comment by Kejiasir** [comment]
嗯嗯，好的，明天回公司我写个demo

Heath Wang <notifications@github.com>于2020年4月26日 周日09:58写道：

**Comment by HeathWang** [comment]
> 嗯嗯，好的，明天回公司我写个demo Heath Wang <notifications@github.com>于2020年4月26日 周日09:58写道：
> […](#)

今天上班的人留下了心酸的泪水

**Comment by Kejiasir** [comment]
😂😂我们大小周，昨天上班，因为五一调休，这个月全改成单休了，累的不行。

请问有建交流群吗，或者加你QQ或微信交流可以吗，看到你留的二维码已经过期了😅

Heath Wang <notifications@github.com>于2020年4月26日 周日11:19写道：

**Comment by HeathWang** [comment]
@Kejiasir 已更新二维码，我不知道这个会过期

**Comment by Kejiasir** [comment]
好的，谢谢👍

Heath Wang <notifications@github.com>于2020年4月26日 周日11:44写道：
