### ISSUE TITLE
iOS14设置模糊效果会导致底部页面变灰

### ISSUE THREAD

**Issue by CuanXiangDeYun** [HeathWang/HWPanModal#58]
如题,感谢作者开源优秀的框架.致谢.

**Comment by HeathWang** [comment]
好的，我排查一下，目前还没安装iOS14

**Comment by QingyuHu** [comment]
HWVisualEffectView 在iOS14上有问题，貌似是私有方法变了

**Comment by HeathWang** [comment]
HWBackgroundConfig请配置`HWBackgroundBehaviorSystemVisualEffect`，稍后我看看这个问题

**Comment by HeathWang** [comment]
iOS14无法使用，closed
