### ISSUE TITLE
子VC里面，假如有UITableView，无法下滑UITableView，直接会dismiss子VC

### ISSUE THREAD

**Issue by KangLeon** [HeathWang/HWPanModal#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
请参照demo来编写代码，子vc也需要传递tableview让框架知道
