### ISSUE TITLE
0.7.7版本根据demo设置打开VC里面tableView数据是异步网络加载，结果刷新后，无法滚动

### ISSUE THREAD

**Issue by mihaibo** [HeathWang/HWPanModal#61]
根据最新版本照着Demo设置，vc里面有tableview，数据会异步网络刷新。刷新出来tableview始终无法滚动，以下是我对应的代理实现，我也不晓得是不是bug。
panScrollable 我有返回当前vc的tableview，但纳闷不能滚动。

以下是我实现的相关代理实现
#pragma mark - HWPanModalPresentable

- (PanModalHeight)longFormHeight {
    return PanModalHeightMake(PanModalHeightTypeMax, 100);
}

- (PanModalHeight)shortFormHeight {
    return PanModalHeightMake(PanModalHeightTypeMaxTopInset, 200);
}

- (BOOL)showDragIndicator {
    return NO;
}

- (UIScrollView *)panScrollable{
    return self.tableView;
}
- (BOOL)isPanScrollEnabled{
    return YES;
}

**Comment by HeathWang** [comment]
数据刷新完成后需要手动调用刷新方法 `[self hw_panModalSetNeedsLayoutUpdate];`。
```
        self.dataSource = list;
        [self.tableView reloadData];
        [self.indicatorView stopAnimating];
        [self hw_panModalSetNeedsLayoutUpdate];
        
        if (self.tableView.mj_header.isRefreshing) {
            [self.tableView.mj_header endRefreshing];
        }
```

**Comment by HeathWang** [comment]
hi，如果没有问题，我将关闭该bug

**Comment by mihaibo** [comment]
没有了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Heath Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 下午2:43
收件人: "HeathWang/HWPanModal"<HWPanModal@noreply.github.com&gt;; 
抄送: "米海波"<mihaibo1@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HeathWang/HWPanModal] 0.7.7版本根据demo设置打开VC里面tableView数据是异步网络加载，结果刷新后，无法滚动 (#61)





 
hi，如果没有问题，我将关闭该bug

**Comment by mihaibo** [comment]
3Q




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Heath Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 下午2:43
收件人: "HeathWang/HWPanModal"<HWPanModal@noreply.github.com&gt;; 
抄送: "米海波"<mihaibo1@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HeathWang/HWPanModal] 0.7.7版本根据demo设置打开VC里面tableView数据是异步网络加载，结果刷新后，无法滚动 (#61)





 
hi，如果没有问题，我将关闭该bug
