### ISSUE TITLE
demo 不能正常运行

### ISSUE THREAD

**Issue by Brances** [HeathWang/HWPanModal#64]
yld: Library not loaded: @rpath/HWPanModal.framework/HWPanModal
  Referenced from: /private/var/containers/Bundle/Application/3E40B8CA-6017-468D-83B2-14084FB73BBC/HWPanModalDemo.app/HWPanModalDemo
  Reason: no suitable image found

**Comment by Brances** [comment]
模拟器没问题，真机跑不起来

**Comment by HeathWang** [comment]
奇怪，没人报这个问题，pod update执行没
