### ISSUE TITLE
tableView 高度动态的计算出来的，tabview手势失效

### ISSUE THREAD

**Issue by Dengfulei** [HeathWang/HWPanModal#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
请贴出代码，或者详细使用步骤。

**Comment by Dengfulei** [comment]
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return [self.tagTypes count] ? [self.tagTypes count] + 1 : 0;
}
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 1;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (indexPath.section == 0) {
        return [XYRangeTableViewCell cellHeight:self.searchLocalObj];
    }
    XYTagTypeObj *tag = self.tagTypes[indexPath.section - 1];
    
    return tag.isExpand ? tag.cellFullHeight : tag.cellHeight;
}

**Comment by Dengfulei** [comment]
目前貌似静态固定区，固定高，上滑tablview才能滚动

**Comment by HeathWang** [comment]
改变高度后需要调用`- (void)hw_panModalSetNeedsLayoutUpdate;`
请查阅md或者示例代码。

**Comment by Dengfulei** [comment]
谢谢，但是tableView据底部有大概44这样的高度
