### ISSUE TITLE
Can't Slide Up or Slide Down then keyboard of device open

### ISSUE THREAD

**Issue by UmerAfzal1** [HeathWang/HWPanModal#67]
**Keyboard open then user interaction disable with contentview **
Any view contain textview or textfield then keyboard open then view can't swipe up or down at this stage

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS13.1]

**Comment by HeathWang** [comment]
Please show me the code about your viewController.

**Comment by UmerAfzal1** [comment]
Hi 

I implement same as your sample project code facing issue then any textfield in panview start typing then pan view not move up or down.
For This verify i connect developer account with your code or test same issue facing. It's work only on simulator but real device facing same issue.

I created a video for you please check.
https://photos.app.goo.gl/2HkycevCtqUXmqBy9

Thanks

**Comment by HeathWang** [comment]
Thanks, I will check it ASAP.

**Comment by HeathWang** [comment]
> Hi
> 
> I implement same as your sample project code facing issue then any textfield in panview start typing then pan view not move up or down.
> For This verify i connect developer account with your code or test same issue facing. It's work only on simulator but real device facing same issue.
> 
> I created a video for you please check.
> https://photos.app.goo.gl/2HkycevCtqUXmqBy9
> 
> Thanks

I have tested my example, it worked right.
I only see one textfiled in your screen record, did you change something?

**Comment by UmerAfzal1** [comment]
Hi 
No Just download your code or connect developer account and run your code on device and test one text field option just start typing and show keyboard at this stage popup not swipe up or down

**Comment by UmerAfzal1** [comment]
During typing i can't view scroll up or down on real device after resign keyboard working fine but issue in facing on keyboard open time. Kindly check this issue because i use in my own product and i will launch soon as possible. Thanks for kind interaction

**Comment by UmerAfzal1** [comment]
Issue is not Dismiss view even i ready set allowsDragToDismiss Yes in case of keyPad open, If keypad not open working fine.

**Comment by HeathWang** [comment]
hi, I run example project on iPhone8 iOS 13.6, it works well.

**Comment by UmerAfzal1** [comment]
Ohh Yes I found it Issue in a Single Text Field Then I use keypad on single Text Field and scroll down for dismiss it no working But in Case of multiple Text Field that show in tableview it's working. 
Can you add allowsDragToDismiss Functionality without using tableView or scrollview in a pan view. if already have in please tell me how i'm use this.
Thanks

**Comment by HeathWang** [comment]
> Ohh Yes I found it Issue in a Single Text Field Then I use keypad on single Text Field and scroll down for dismiss it no working But in Case of multiple Text Field that show in tableview it's working.
> Can you add allowsDragToDismiss Functionality without using tableView or scrollview in a pan view. if already have in please tell me how i'm use this.
> Thanks

yeah, current version can solution this issue.

Solution 1:
implement two methods let you can drag when you want to scroll or tap "return" on keyboard.

```
- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    [textField resignFirstResponder];
    return YES;
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
    [self.view endEditing:YES];
}
```

Solution 2:
I support api handle keyboard behavior, `- (BOOL)isAutoHandleKeyboardEnabled;`, you can overwrite it and return NO for this method, BUT you need update the VC's view frame by yourself.

**Comment by UmerAfzal1** [comment]
Hi,
Solution 1 working perfect thanks for kind response and solve my issue on time.

**Comment by HeathWang** [comment]
nice.
