### ISSUE TITLE
HWPanModalPresentationDelegate dealloc

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#69]
正常`[self presentPanModal:vc];`调用， 控制器 不显示 ， 控制台输出`-[HWPanModalPresentationDelegate dealloc]`

**Comment by fuchenxi** [comment]
貌似是 iOS14 下的bug，输出 -[HWPanModalPresentationDelegate dealloc]， 系统转场动画不显示了， 麻烦尽快修复

**Comment by HeathWang** [comment]
怎么出现的，我在iOS14的模拟器上都可以正常弹出

**Comment by 275080225** [comment]
遇到同样问题，iOS14

**Comment by 275080225** [comment]
原因找到了，导入了一个库调用了viewControllerToPresent.modalPresentationStyle = UIModalPresentationFullScreen;导致的

**Comment by HeathWang** [comment]
> 原因找到了，导入了一个库调用了viewControllerToPresent.modalPresentationStyle = UIModalPresentationFullScreen;导致的

具体哪个库，给其他人一点指导

**Comment by 275080225** [comment]
直接搜索modalPresentationStyle能找到
我用的这个：
https://github.com/HDB-Li/UIViewController

**Comment by HeathWang** [comment]
> https://github.com/HDB-Li/UIViewController

Thanks.

**Comment by HeathWang** [comment]
无回复，关闭issue
