### ISSUE TITLE
存在手势冲突，下拉页面内的tableview的时候，页面也会跟着下拉。

### ISSUE THREAD

**Issue by yangyunen** [HeathWang/HWPanModal#70]
如题

**Comment by summonerriftofficial** [comment]
same

**Comment by HeathWang** [comment]
show me the code.

**Comment by YangsCalvin** [comment]
https://github.com/HeathWang/HWPanModal/issues/75#issuecomment-723919580

**Comment by YangsCalvin** [comment]
参考此处 https://github.com/HeathWang/HWPanModal/issues/75#issuecomment-723919580

**Comment by HeathWang** [comment]
> 参考此处 [#75 (comment)](https://github.com/HeathWang/HWPanModal/issues/75#issuecomment-723919580)

Thanks.
