### ISSUE TITLE
可以添加一个点击背景的事件回调？

### ISSUE THREAD

**Issue by Danie1s** [HeathWang/HWPanModal#73]
我的业务需求：点击背景后会弹窗，询问用户是否需要dismiss

**Comment by HeathWang** [comment]
目前没有此事件回调，但是你当点击背景的时候，会触发`- (BOOL)allowsTapBackgroundToDismiss;`回调
你可以返回NO，然后弹框

**Comment by Danie1s** [comment]
这样也可以
