### ISSUE TITLE
可以增加一个选项决定是否调用"[fromVC beginAppearanceTransition:NO animated:YES];"?

### ISSUE THREAD

**Issue by Danie1s** [HeathWang/HWPanModal#74]
由于实际上fromVC并没有移除，所以我觉得不应该调用这个方法

**Comment by HeathWang** [comment]
`If you are implementing a custom container controller, use this method to tell the child that its views are about to appear or disappear. Do not invoke viewWillAppear:, viewWillDisappear:, viewDidAppear:, or viewDidDisappear: directly.`
beginAppearanceTransition为NO，并没有表示移除该vc，只是表示vc即将disappear

**Comment by Danie1s** [comment]
你可以尝试一下自带的几个 present style，如果是没有移除 fromVC 的 view，一般是不会调用 beginAppearanceTransition 的，只有present 出来的 vc 是全屏的，才会移除 fromVC 的 view。

如果没有移除 fromVC 的 view，那就不应该 beginAppearanceTransition 触发 fromVC 的那几个方法吧？

**Comment by HeathWang** [comment]
可以，后面加一个api

**Comment by Danie1s** [comment]
感谢

**Comment by HeathWang** [comment]
@Danie1s 

请更新至0.8.1，方法返回NO即可关闭

- (BOOL)shouldEnableAppearanceTransition {
    return NO;
}
