### ISSUE TITLE
横向滚动和下滑手势有冲突

### ISSUE THREAD

**Issue by iosdevcoding** [HeathWang/HWPanModal#76]
感谢作者开源！

横向滚动和下滑手势有冲突，即使把这里改为nil，还是存在问题。

- (UIScrollView *)panScrollable {
    return nil;
}

**Comment by HeathWang** [comment]
从交互上来说，该框架的主要作用就是为了下滑dismiss，如果你需要横向滚动，只能禁用掉框架内的手势操作。
你需要额外提供一个关闭按钮来让用户关闭弹出视图层。

使用一下代码禁用手势：

```
- (BOOL)shouldRespondToPanModalGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer {
    return NO;
}
```
当然你也可以判断当前手势所在位置是否在滚动列表里来返回不同bool值。

**Comment by fuchenxi** [comment]
如果内部为collectionView， 能否根据我滑动collectionView的方向进行判断？
横向滑动禁用， 纵向激活
