### ISSUE TITLE
如何禁止掉内部处理键盘的操作

### ISSUE THREAD

**Issue by thomas-cao** [HeathWang/HWPanModal#79]
在使用的时候，我的页面底部有个输入框，再点击输入框的时候，页面跟随键盘弹出了，请问怎么禁止掉这个操作。我想让键盘显示在最上层 而不是将页面顶上去

**Comment by propertyChen** [comment]
hi 朋友，我遇见一样的问题，我想做一个类似于抖音的评论列表，最底部有个评论输入框（YYTextView），输入时一直把页面顶上去了。看你关了这个issues,是有解决方案了？
