### ISSUE TITLE
请问如何默认固定 View 在底部，而不是 Present 出来呢？

### ISSUE THREAD

**Issue by geekdmm0xff** [HeathWang/HWPanModal#80]
![美团单车](https://user-images.githubusercontent.com/10804912/101235642-05680780-3705-11eb-91a2-37040314a9e3.jpeg)
这种效果可以支持吗？

**Comment by HeathWang** [comment]
这种最好的还是放一个tableview在地图上面，然后时间透传下去。
目前不支持。
