### ISSUE TITLE
这是抄的slack的panmodel吧，都不说一下的么

### ISSUE THREAD

**Issue by ishall1** [HeathWang/HWPanModal#82]

**Comment by vmormont** [comment]
Objective-C version of PanModal

**Comment by HeathWang** [comment]
@ishall1 
`
HWPanModal is used to present controller and drag to dismiss. Similar with iOS13 default present Modal style.

Inspired by PanModal, thanks.
`
我没有说？而且你看过源码吗？我的功能和抄的完全一致吗？

**Comment by ishall1** [comment]
我早都关了，你又何必这么冲呢
