### ISSUE TITLE
有个想法想问一下

### ISSUE THREAD

**Issue by wuvdan** [HeathWang/HWPanModal#83]
`A Controller` 弹出 `B Controller`（实现`HWPanModalPresentable`），当B页面消失的时候，为什么每次A页面都会调用`- (void)viewWillAppear:(BOOL)animated`，这样`A Controller`就会出现很多意外情况，请问有什么办法可以解决？

**Comment by HeathWang** [comment]
https://github.com/HeathWang/HWPanModal/issues/74
后续会添加开关是否触发`viewWillAppear`

**Comment by HeathWang** [comment]
请更新至0.8.1，方法返回NO即可关闭
```
- (BOOL)shouldEnableAppearanceTransition {
    return NO;
}
```

**Comment by fuchenxi** [comment]
以前做短视频播放时，弹出评论视频总是受生命周期影响。
