### ISSUE TITLE
dismiss时侧滑手势的速度判断能否抛出来，可以使用户自定义。

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#84]
需求：我需要更灵活的触发dismiss， 速度比你初始值小一些。

`- (BOOL)isVelocityWithinSensitivityRange:(CGFloat)velocity {
    return (fabs(velocity) - (1000.00f * (1 - kSnapMovementSensitivity))) > 0;
}
`

外部抛出个方法 return 0 ~ 1 的？

**Comment by HeathWang** [comment]
可以

**Comment by HeathWang** [comment]
HWPanModal (0.8.4)已添加
```
/**
 min Velocity from Vertical direction that trigger dismiss action.
 Default is 300.0
 */
- (CGFloat)minVerticalVelocityToTriggerDismiss;
```
提供手势加速度即可
