### ISSUE TITLE
大侠 为啥执行[self dismissViewControllerAnimated:YES completion:NULL] 后不会调 panModalDidDismissed 这个回调

### ISSUE THREAD

**Issue by heliang219** [HeathWang/HWPanModal#86]
大侠 为啥执行[self dismissViewControllerAnimated:YES completion:NULL] 后不会调 panModalDidDismissed 这个回调

**Comment by HeathWang** [comment]
我排查下

**Comment by HeathWang** [comment]
> 大侠 为啥执行[self dismissViewControllerAnimated:YES completion:NULL] 后不会调 panModalDidDismissed 这个回调

如果你是自己手动执行[self dismissViewControllerAnimated:YES completion:NULL]，确实不会调用panModalDidDismissed，因为内部无法感知主动调用，你可以在completion中处理你的逻辑。

**Comment by heliang219** [comment]
可以是可以 我目前是这么解决的 那你内部可以做到统一吗？毕竟都是dissMiss 在一个地方处理当然是最好 如果不好处理那就算了哈 我只是给个建议

**Comment by HeathWang** [comment]
目前我没有办法知道你主动调用dismissViewControllerAnimated，后面我看看能不能统一掉
