### ISSUE TITLE
感觉当Pan出来是一个nav的时候用起来怪怪的

### ISSUE THREAD

**Issue by birdmichael** [HeathWang/HWPanModal#87]
PanModalDefault分类，是否需要添加一个检测，如果是UINavigationController,去拿Root的的逻辑呢？因为一个页面去创建一个新的导航，为了实现分类有点怪。

**Comment by HeathWang** [comment]
最初的设计时hook UINavigationController的方式去实现的，但是会对其他框架造成影响，所以修改为自己去包裹nav。
