### ISSUE TITLE
present出navigationController之后，操作逻辑很怪

### ISSUE THREAD

**Issue by pstkqzy** [HeathWang/HWPanModal#88]
1.present出navigationController之后，push到其他Controller滑动返回时，不是返回上一个Controller，而点击返回按钮可以返回上一个Controller，能不能滑动返回时可以返回上一个Controller

**Comment by pstkqzy** [comment]
https://user-images.githubusercontent.com/17919078/112571953-1a87b400-8e24-11eb-82a2-331121f03e37.MP4

这是demo演示

**Comment by HeathWang** [comment]
过度是有点问题，目前是个问题

**Comment by HeathWang** [comment]
> 1.present出navigationController之后，push到其他Controller滑动返回时，不是返回上一个Controller，而点击返回按钮可以返回上一个Controller，能不能滑动返回时可以返回上一个Controller

滑动返回自己可以控制的
