### ISSUE TITLE
panScrollable 使用问题

### ISSUE THREAD

**Issue by fuchenxi** [HeathWang/HWPanModal#91]
使用panScrollable 返回一个collectionView导致collectionView不可滚动， 点击cell之后恢复正常

	- (UIScrollView *)panScrollable {

		return self.collectionView;
	}

使用了以下控件和布局

	[self.headerView mas_makeConstraints:^(MASConstraintMaker *make) {
	
		make.leading.trailing.top.equalTo(self.view);
		make.height.mas_equalTo(kScale(48));
	}];
	
	[self.collectionView mas_makeConstraints:^(MASConstraintMaker *make) {
		
		make.top.equalTo(self.headerView.mas_bottom);
		make.leading.trailing.equalTo(self.view);
		make.bottom.equalTo(self.toolView.mas_top);
	}];
	
	[self.toolView mas_makeConstraints:^(MASConstraintMaker *make) {
		make.leading.trailing.equalTo(self.view);
		make.bottom.equalTo(self.view).offset(-kSafeAreaBottom);
		make.height.mas_equalTo(kScale(48));
	}];

**Comment by HeathWang** [comment]
你好，请提供完整可测试的代码。

**Comment by WYK45** [comment]
遇到了同样的问题，我想应该很好复现吧

**Comment by WYK45** [comment]
我的在点击cell之后也没有恢复

**Comment by mlch911** [comment]
估计是没调 `panModalSetNeedsLayoutUpdate`
