### ISSUE TITLE
页面内嵌多个 scrollView，手势冲突

### ISSUE THREAD

**Issue by shanglina** [HeathWang/HWPanModal#92]
您好，页面有个scrollView ，scrollView上横向放置 5 个 collectionView， 左右横滑时，角度倾斜会出发手势返回。
这个问题怎么处理呢？ 如果您有空的话可以指教下吗？谢谢您，辛苦了

**Comment by HeathWang** [comment]
```
- (BOOL)shouldRespondToPanModalGestureRecognizer:(UIPanGestureRecognizer *)panGestureRecognizer {
    CGPoint point = [panGestureRecognizer locationInView:self];
    if (CGRectContainsPoint(self.collectionView.frame, point)) {
        return NO;
    }
    
    return YES;
    
}
```

可以实现上面的协议方法，判断当前手势是否在5个collection中，在的话返回NO即可。

**Comment by shanglina** [comment]
谢谢您回复，我试了一下还是有点问题，下拉的时候 会有散架的感觉。
https://github.com/shanglina/HWPan
如果您有空的话可以再看看吗？麻烦了哦

**Comment by HeathWang** [comment]
我看了下，你这种是全部覆盖，建议不使用拖拽下拉dismiss的操作，把上面协议完全禁用掉，设计一个按钮点击关闭。
