### ISSUE TITLE
Custom sheet behaviour

### ISSUE THREAD

**Issue by vicmosin** [HeathWang/HWPanModal#93]
Is this conceptually possible to change the direction of the sheet? I.e. having it animating other way around, from top to bottom?

Thank you in advance

**Comment by HeathWang** [comment]
strange animation，it can be implemented，but I need more detail what you want.

**Comment by vicmosin** [comment]
@HeathWang yeah, that's why I asked whether it's possible in general.. Not sure what apple guide lines say about it. Basically, what I need is exactly the opposite of current behaviour -> sheet comes from top of the screen. Here is some android example of such lib (which allows to configure the animation direction): https://github.com/orhanobut/dialogplus

**Comment by HeathWang** [comment]
> @HeathWang yeah, that's why I asked whether it's possible in general.. Not sure what apple guide lines say about it. Basically, what I need is exactly the opposite of current behaviour -> sheet comes from top of the screen. Here is some android example of such lib (which allows to configure the animation direction): https://github.com/orhanobut/dialogplus

You can use my another framework [HWPopController](https://github.com/HeathWang/HWPopController), it provides different alert style. it's not good to add from top to bottom behaviour into current framework, this project main function is use drag down to dismiss alert.
