### ISSUE TITLE
不应该自动调整 panScrollable 的 contentInset

### ISSUE THREAD

**Issue by mlch911** [HeathWang/HWPanModal#94]
https://github.com/HeathWang/HWPanModal/blob/94c31b62b84d5bca02d9db70577a84f639cbe882/Sources/Mediator/HWPanModalPresentableHandler.m#L394

应该和其它参数一样，在 `HWPanModalPresentable` 里加一个设置是否开启这个功能。
或者在 `PanModalHeight` 为 `.content` 时才去设置 `contentInset`。

**Comment by HeathWang** [comment]
现在改这个是对你有什么影响吗？

**Comment by mlch911** [comment]
我有个 `panScrollable`，但它 `contentInset` 就是 .zero 就行，而不应该自动给它设置。

**Comment by HeathWang** [comment]
了解，后面我新增一个方法，默认自动调整，如果你不想用默认的，可以重写方法并关闭。

**Comment by HeathWang** [comment]
0.8.5版本增加新的api可以控制了
`- (BOOL)shouldAutoSetPanScrollContentInset;`
