### ISSUE TITLE
怎么修改弹出框大小呢，主要是宽，有提供方法么 

### ISSUE THREAD

**Issue by Marcello168** [HeathWang/HWPanModal#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HeathWang** [comment]
弹出来的视图是你自己控制的，你在ViewController里放一个你想要的宽view不就好了

**Comment by Marcello168** [comment]
> 弹出来的视图是你自己控制的，你在ViewController里放一个你想要的宽view不就好了

👌🏻
