### ISSUE TITLE
UIScrollView的showsVerticalScrollIndicator失效

### ISSUE THREAD

**Issue by rhwish** [HeathWang/HWPanModal#96]
使用presentPanModal展示一个NavigationController，NavigationController的rootVC中使用UIScrollview，此时设置UIScrollView的showsVerticalScrollIndicator为NO无效

**Comment by HeathWang** [comment]
请问你是怎么设置的,请使用该协议设置
```
- (BOOL)showsScrollableVerticalScrollIndicator {
    return NO;
}

```

**Comment by rhwish** [comment]
可以了，十分感谢
