### ISSUE TITLE
无法支持只改变高度的需求。

### ISSUE THREAD

**Issue by biostome** [HeathWang/HWPanModal#98]
大概看了下代码，想根据需求修改下，但方法声明貌似都是修改y值的。整体结构也不是很了解。
按照我这需求估计可能需要大改。不过还是希望能进行优化。
需求是这样的：
1 初始一个高度，然后通过拖拽修改控制器视图的高度，非Y值。
2 弹出 视图后，透明部分可以穿透点击。

**Comment by HeathWang** [comment]
> 2 弹出 视图后，透明部分可以穿透点击。
这个已经可以实现了，请使用`- (BOOL)allowsTouchEventsPassingThroughTransitionView;`
你的第一个需求没看懂，你要拖拽改变控制器视图的高度，不适用改组件。

**Comment by HeathWang** [comment]
长期未回复，关闭
