### ISSUE TITLE
关于dismiss

### ISSUE THREAD

**Issue by MuRanJiangXia** [HeathWang/HWPanModal#99]
如果我将允许TouchEventsPassingThroughTransitionView设置为no，允许TapBackgroundToDismiss将回调；
我需要在allowsTouchEventsPassingThroughTransitionView 设置为no时，可以得到点击背景回调事件

**Comment by MuRanJiangXia** [comment]
haole

**Comment by MuRanJiangXia** [comment]
调试了一下还是有问题

**Comment by HeathWang** [comment]
你需要解决什么问题，需要点击背景的回调？

**Comment by HeathWang** [comment]
不同的状态下- (BOOL)allowsTapBackgroundToDismiss;返回不同值不就好了

**Comment by MuRanJiangXia** [comment]
> 不同的状态下- (BOOL)allowsTapBackgroundToDismiss;返回不同值不就好了
前提是我设置了这个属性
allowsTouchEventsPassingThroughTransitionView ，在PresentationStateShort 为yes PresentationStateLong 为no，然后在long的时候就不会有allowsTapBackgroundToDismiss回调了

**Comment by HeathWang** [comment]
大哥下次问题可以描述清楚点，allowsTouchEventsPassingThroughTransitionView设置后，再变更，没有更新，我需要修改下

**Comment by HeathWang** [comment]
HWPanModal (0.8.6) successfully published。
使用以上版本。

```
- (void)didChangeTransitionToState:(PresentationState)state {
    [self hw_panModalUpdateUserHitBehavior];
}

- (BOOL)allowsTouchEventsPassingThroughTransitionView {
    if (self.hw_presentationState == PresentationStateShort) {
        return YES;
    } else {
        return NO;
    }
}
```

**Comment by MuRanJiangXia** [comment]
> HWPanModal (0.8.6) successfully published。
> 使用以上版本。
> 
> ```
> - (void)didChangeTransitionToState:(PresentationState)state {
>     [self hw_panModalUpdateUserHitBehavior];
> }
> 
> - (BOOL)allowsTouchEventsPassingThroughTransitionView {
>     if (self.hw_presentationState == PresentationStateShort) {
>         return YES;
>     } else {
>         return NO;
>     }
> }
> ```

恩恩，谢谢
